import { Recall } from "./types";

// 아래 데이터는 국토교통부 발표를 인용한 언론 보도 및 자동차리콜센터(car.go.kr) 공개 정보를 바탕으로
// 정리한 실제 리콜 사례입니다. 각 항목의 출처(source/sourceUrl)를 통해 원문을 확인할 수 있습니다.
// 정확한 개별 차량의 리콜 대상 및 조치 여부는 반드시 자동차리콜센터에서 확인해야 합니다.
export const recalls: Recall[] = [
  {
    id: "r-palisade-seat-2026",
    vehicleSlugs: ["hyundai/palisade"],
    manufacturer: "현대",
    affectedModelsText: "팰리세이드, 팰리세이드 하이브리드(미판매 재고 포함) 5만7,987대",
    title: "2·3열 전동시트 제어기 소프트웨어 관련 리콜",
    recallDate: "2026-03-20",
    applicableYears: [2023, 2024, 2025],
    defect:
      "2·3열 전동시트 제어기 소프트웨어 설계가 미흡해 탑승자나 사물과의 접촉을 정상적으로 감지하지 못하는 문제가 확인됨",
    risk: "전동시트 작동 중 탑승자나 사물이 끼이는 안전사고로 이어질 가능성",
    remedy:
      "무선 소프트웨어 업데이트(OTA)를 통해 전동시트 작동 해제 방식 변경, 접촉 감지 구간 확대, 자동 접힘 기능 작동 조건 강화",
    affectedCount: 57987,
    recallType: "자발적 리콜",
    status: "related",
    source: "아주경제 (국토교통부 발표 인용)",
    sourceUrl: "https://www.ajunews.com/view/20260324083104954",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-palisade-seatbelt-2026",
    vehicleSlugs: ["hyundai/palisade"],
    manufacturer: "현대",
    affectedModelsText: "팰리세이드 4만1,143대",
    title: "3열 좌측 안전띠 버클 배선 관련 리콜",
    recallDate: "2026-04-10",
    applicableYears: [2023, 2024, 2025],
    defect:
      "3열 좌측 안전띠 버클 배선 설계가 미흡해 안전띠를 체결하지 않아도 경고장치가 작동하지 않는 문제",
    risk: "탑승자가 안전띠 미체결 상태를 인지하지 못할 가능성",
    remedy: "국토교통부 발표 기준 시정조치 진행 (세부 방법은 공식 출처 확인)",
    affectedCount: 41143,
    recallType: "자발적 리콜",
    status: "related",
    source: "아주경제 (국토교통부 발표 인용)",
    sourceUrl: "https://www.ajunews.com/view/20260324083104954",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-sonata-airbag-2024",
    vehicleSlugs: ["hyundai/sonata"],
    manufacturer: "현대",
    affectedModelsText: "쏘나타 등 2개 차종 31만2,744대",
    title: "에어백 제어장치 설계오류 관련 리콜",
    recallDate: "2024-10-11",
    defect: "에어백 제어장치 설계오류로 내부 소자가 손상되어 에어백이 전개되지 않을 가능성",
    risk: "사고 발생 시 에어백이 정상적으로 전개되지 않을 가능성",
    remedy:
      "제작사가 소유자에게 우편 및 휴대전화 문자로 시정 방법을 안내하며, 사전에 자비로 수리한 경우 비용 보상 신청 가능",
    affectedCount: 312744,
    recallType: "리콜",
    status: "related",
    source: "뉴스핌 (국토교통부 발표 인용)",
    sourceUrl: "https://www.newspim.com/news/view/20241008001080",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-avante-cvt-2026",
    vehicleSlugs: ["hyundai/avante"],
    manufacturer: "현대",
    affectedModelsText: "아반떼 13만283대",
    title: "무단변속기(CVT) 내부 이물질 유입 관련 리콜",
    recallDate: "2026-01-19",
    defect: "무단변속기 부품 내부로 이물질이 유입되어 구동력이 정상적으로 전달되지 않을 가능성",
    risk: "주행 중 구동력이 끊길 가능성",
    remedy:
      "자동변속기 부품을 정비해 이물질 유입을 방지하는 시정조치 진행. 우편·문자 안내, 사전 자비 수리 시 비용 보상 신청 가능",
    affectedCount: 130283,
    recallType: "리콜",
    status: "related",
    source: "오토데일리 (국토교통부 발표 인용)",
    sourceUrl: "https://www.autodaily.co.kr/news/articleView.html?idxno=540775",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-sorento-hev-seatbelt-2023",
    vehicleSlugs: ["kia/sorento"],
    manufacturer: "기아",
    affectedModelsText: "쏘렌토 하이브리드(HEV) 8만1,608대",
    title: "앞좌석 안전띠 조절장치(프리텐셔너) 관련 리콜",
    recallDate: "2023-08-16",
    defect: "앞좌석 안전띠 조절장치 내부 부품(가스발생기) 불량",
    remedy: "자발적 시정조치(리콜) 실시",
    affectedCount: 81608,
    recallType: "자발적 리콜",
    status: "related",
    source: "뉴시스",
    sourceUrl: "https://www.newsis.com/view/NISX20230816_0002415834",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-carnival-fire-2026",
    vehicleSlugs: ["kia/carnival"],
    manufacturer: "기아",
    affectedModelsText: "카니발 9만9,889대",
    title: "엔진 내부 부품 체결 불량 관련 리콜 (화재 위험)",
    recallDate: "2026-08-06",
    defect: "엔진 내부 부품의 너트 체결 불량으로 연료가 누유되어 화재가 발생할 가능성",
    risk: "주행 중 또는 주정차 중 화재 발생 가능성",
    remedy: "국토교통부 발표 기준 시정조치 진행 (세부 방법은 공식 출처 확인)",
    affectedCount: 99889,
    recallType: "리콜",
    status: "related",
    source: "경향신문 (국토교통부 발표 인용)",
    sourceUrl: "https://www.khan.co.kr/article/202608060730001",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-gv80-isg-2020",
    vehicleSlugs: ["genesis/gv80"],
    manufacturer: "제네시스",
    affectedModelsText: "GV80 823대",
    title: "ISG(스탑앤고) 소프트웨어 오류 관련 리콜",
    recallDate: "2020-02-27",
    defect:
      "ISG 장치의 소프트웨어 오류로 인한 변속 불량. 주차 중 기어를 P로 두면 ISG 작동으로 시동이 꺼지고, 재시동 후 D→R→D 순으로 기어를 조작하면 D 모드에서도 차량이 후진하는 현상 발생",
    risk: "운전자 의도와 다르게 차량이 후진할 가능성",
    remedy: "소프트웨어 업데이트 실시",
    affectedCount: 823,
    recallType: "리콜",
    status: "related",
    source: "모터그래프",
    sourceUrl: "https://www.motorgraph.com/news/articleView.html?idxno=25179",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-bmw-520d-egr-2021",
    vehicleSlugs: ["bmw/520d"],
    manufacturer: "BMW",
    affectedModelsText: "BMW 520d 등 31개 차종 22만1,172대",
    title: "배기가스재순환장치(EGR쿨러) 균열 관련 리콜",
    recallDate: "2021-03-31",
    defect: "2017년 이후 개선된 EGR쿨러 일부 제품에서 균열이 발생해 화재 위험이 있는 것으로 확인",
    risk: "냉각수 누수 및 화재 발생 가능성",
    remedy:
      "냉각수 누수 위험도가 높은 차량(약 10만7,731대)은 EGR쿨러 교체, 최근 생산된 EGR쿨러 장착 차량(약 11만3,441대)은 점검 후 필요시 교체",
    affectedCount: 221172,
    recallType: "리콜",
    status: "related",
    source: "뉴시스 (국토교통부 발표 인용)",
    sourceUrl: "https://www.newsis.com/view/NISX20210331_0001390672",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-tesla-hood-2024",
    vehicleSlugs: ["tesla/model-3"],
    manufacturer: "테슬라",
    affectedModelsText: "테슬라 Model 3·Model Y 등 4개 차종 6만6,489대",
    title: "후드 오픈 감지 소프트웨어 오류 관련 리콜",
    recallDate: "2024-08-22",
    defect: "후드 관련 소프트웨어 오류로 주행 중 후드가 열려 있어도 운전자가 이를 감지하지 못할 가능성",
    risk: "주행 중 후드가 열려 시야 확보에 지장을 줄 가능성",
    remedy: "무선 소프트웨어 업데이트(OTA) 등 국토교통부 발표 기준 조치 (세부 방법은 공식 출처 확인)",
    affectedCount: 66489,
    recallType: "자발적 리콜",
    status: "related",
    source: "경기일보 (국토교통부 발표 인용)",
    sourceUrl: "https://www.kyeonggi.com/article/20240821580001",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-tesla-seatbelt-2022",
    vehicleSlugs: ["tesla/model-3"],
    manufacturer: "테슬라",
    affectedModelsText: "테슬라 Model 3·Model Y 3만3,337대",
    title: "안전벨트 미착용 경고음 미작동 관련 리콜",
    recallDate: "2022-02-17",
    defect: "제어장치 소프트웨어 오류로 안전벨트를 착용하지 않아도 경고음이 울리지 않는 문제",
    risk: "안전벨트 미착용 상태로 주행할 가능성",
    remedy: "테슬라 서비스센터 무상 수리 또는 무선 소프트웨어 업데이트로 조치",
    affectedCount: 33337,
    recallType: "리콜",
    status: "related",
    source: "매일신문",
    sourceUrl: "https://www.imaeil.com/page/view/2022021709075461319",
    updatedAt: "2026-09-12",
  },

  // 아래부터는 한국교통안전공단이 공공데이터포털(data.go.kr)에 공개한
  // "자동차결함 리콜현황" 파일데이터(2025-12-31 기준, 이용허락범위 제한 없음)를
  // 근거로 자동 생성한 항목입니다. 같은 리콜사유·리콜개시일을 공유하는 트림들은
  // 하나의 리콜로 묶었고, 생산기간(부터/까지)에 걸친 연도를 applicableYears로 반영했습니다.
  // 원본 파일: data/recalls-2025-raw.csv, 정리 스크립트: scripts/build-official-recalls.py
  {
    id: "r-palisade-20250905",
    vehicleSlugs: ["hyundai/palisade"],
    manufacturer: "현대",
    affectedModelsText: "팰리세이드(LX3), 팰리세이드 하이브리드(LX3 HEV)",
    title: "휠 고정용 너트 체결 불량 관련 리콜",
    recallDate: "2025-09-05",
    productionStart: "2025-01",
    productionEnd: "2025-07",
    applicableYears: [2025],
    defect:
      "팰리세이드(LX3), 팰리세이드HEV (LX3 HEV) 일부 차량에서 휠 고정용 너트 체결 작업 불량으로 주행 중 너트 풀림에 의한 휠 이탈 발생 가능성이 있는 결함 사항 확인",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-palisade-20250916",
    vehicleSlugs: ["hyundai/palisade"],
    manufacturer: "현대",
    affectedModelsText: "팰리세이드(LX3), 팰리세이드 하이브리드(LX3 HEV)",
    title: "전방 후드 래치 설계 미흡 관련 리콜",
    recallDate: "2025-09-16",
    productionStart: "2024-12",
    productionEnd: "2025-07",
    applicableYears: [2024, 2025],
    defect:
      "일부 차량에서 전방 후드 래치 설계 미흡으로 인해 과속방지턱을 주행할 경우 전방 후드 열림 현상이 발생할 수 있으며, 전방 시야 확보가 불가하여 주행 안정성 저하 가능성이 있는 결함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-avante-20250610",
    vehicleSlugs: ["hyundai/avante"],
    manufacturer: "현대",
    affectedModelsText: "아반떼(HD)",
    title: "운전석 에어백 인플레이터 파손 관련 리콜",
    recallDate: "2025-06-10",
    productionStart: "2008-10",
    productionEnd: "2009-07",
    applicableYears: [2008, 2009],
    defect:
      "아반떼(HD) 등 2차종 일부 차량에서 운전석 에어백 전개시 인플레이터의 과도한 내부 압력 증가로 인해 인플레이터 용기가 파손되어 승객이 상해를 입을 가능성이 있는 결함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-santafe-20250709",
    vehicleSlugs: ["hyundai/santafe"],
    manufacturer: "현대",
    affectedModelsText: "싼타페 하이브리드(MX5 HEV)",
    title: "2열 시트 배선 간섭 사이드 에어백 오작동 관련 리콜",
    recallDate: "2025-07-09",
    productionStart: "2024-04",
    productionEnd: "2024-04",
    applicableYears: [2024],
    defect:
      "싼타페 하이브리드(MX5 HEV) 일부 차량에서 차체 하단 와이어링(배선) 경로 설계 불량으로 인해 2열 시트를 접을 시 와이어링(배선)과 시트 회전 장치가 간섭되어 2열 사이드 에어백 오전개 및 미전개 가능성이 있는 결함 사항이 확인",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-sorento-20250124",
    vehicleSlugs: ["kia/sorento"],
    manufacturer: "기아",
    affectedModelsText: "쏘렌토 하이브리드(MQ4 HEV PE), 쏘렌토 (MQ4 PE)",
    title: "바디도메인 제어장치 소프트웨어 오류(전조등 꺼짐) 관련 리콜",
    recallDate: "2025-01-24",
    productionStart: "2023-07",
    productionEnd: "2024-07",
    applicableYears: [2023, 2024],
    defect:
      "바디도메인 제어장치 소프트웨어 오류로 인해 주행 초기 소프트웨어가 리셋되어 재동작하는 경우 전조등이 일시적으로 꺼졌다 켜질 가능성",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-carnival-20251212",
    vehicleSlugs: ["kia/carnival"],
    manufacturer: "기아",
    affectedModelsText: "카니발 하이브리드(KA4 HEV)",
    title: "하이브리드 통합제어기(HPCU) 소손 가능성 관련 리콜",
    recallDate: "2025-12-12",
    productionStart: "2023-12",
    productionEnd: "2025-04",
    applicableYears: [2023, 2024, 2025],
    defect:
      "카니발 하이브리드(KA4 HEV) 일부 차량에서 하이브리드 통합 제어기(HPCU) 소프트웨어 설계 오류로 동절기 원격시동 및 히터 작동 등 전장 고부하 시 하이브리드 통합 제어기(HPCU) 소손 발생 가능성이 있는 결함이 발견됨. HPCU(Hybrid Power Control Unit)는 모터 구동을 위해 인버터, LDC 등을 포함해 제어하는 장치",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-gv80-20250320",
    vehicleSlugs: ["genesis/gv80"],
    manufacturer: "제네시스",
    affectedModelsText: "GV80(JX)",
    title: "계기판 표시 오류 관련 리콜",
    recallDate: "2025-03-20",
    productionStart: "2023-01",
    productionEnd: "2023-10",
    applicableYears: [2023],
    defect:
      "G80(RG3), GV80(JX), GV70(JK), GV70 EV(JK EV) 일부 차량에서 계기판(8인치 계기판 적용 차량) 제어기 소프트웨어 설계 오류로 인해 초기 시동 시 간헐적으로 계기판 이미지가 표출되지 않아 안전기준에 적합하지 않는 사항이 확인됨",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-520d-20251024",
    vehicleSlugs: ["bmw/520d"],
    manufacturer: "BMW",
    affectedModelsText: "520d, 520d xDrive",
    title: "스타터 모터 수분 유입 관련 리콜",
    recallDate: "2025-10-24",
    productionStart: "2016-05",
    productionEnd: "2020-06",
    applicableYears: [2016, 2017, 2018, 2019, 2020],
    defect: "스타터 모터 내 수분이 유입될 가능성이 확인되었습니다.",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-520d-20251204",
    vehicleSlugs: ["bmw/520d"],
    manufacturer: "BMW",
    affectedModelsText: "BMW 520d, BMW 520d Touring, BMW 520d xDrive",
    title: "TAKATA 에어백 스티어링휠 관련 리콜",
    recallDate: "2025-12-04",
    productionStart: "2010-05",
    productionEnd: "2016-10",
    applicableYears: [2010, 2011, 2012, 2013, 2014, 2016],
    defect:
      "최초 판매 당시에는 TAKATA 에어백이 적용되지 않은 스티어링 휠로 출고되었으나, 이후 BMW가 승인한 교체 부품 중 TAKATA 에어백이 적용된 스포츠/M 스포츠 스티어링 휠을 고객이 장착했을 가능성이 확인됨. 해당 휠은 질산암모늄 추진제를 사용해 고온다습 환경에 장기간 노출 시 인플레이터 내부 추진제가 변형될 수 있음",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-model3-20250114",
    vehicleSlugs: ["tesla/model-3"],
    manufacturer: "테슬라",
    affectedModelsText: "Model 3",
    title: "타이어공기압경고장치(TPMS) 소프트웨어 오류 관련 리콜",
    recallDate: "2025-01-14",
    productionStart: "2024-04",
    productionEnd: "2024-08",
    applicableYears: [2024],
    defect:
      "소프트웨어 오류로 TPMS(타이어공기압경고장치)에 이상이 감지된 뒤 차량이 주행 사이클 사이에서 꺼지거나 대기 상태가 되면, TPMS 이상 경고등이 지속적으로 표시되지 않아 관련 안전기준을 준수하지 않는 문제",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-model3-20250205",
    vehicleSlugs: ["tesla/model-3"],
    manufacturer: "테슬라",
    affectedModelsText: "Model 3",
    title: "전원 과전류로 인한 후방카메라 미작동 관련 리콜",
    recallDate: "2025-02-05",
    productionStart: "2024-01",
    productionEnd: "2024-08",
    applicableYears: [2024],
    defect:
      "일부 차량에서 전원 공급 시 과도한 전류가 발생해 차량 컴퓨터가 손상될 가능성이 확인됨. 이로 인해 후방카메라 디스플레이가 정상적으로 작동하지 않을 수 있어 후방보행자 안전장치 관련 안전기준을 준수하지 않는 문제",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  // 아래부터는 한국교통안전공단이 공공데이터포털(data.go.kr)에 공개한
  // "자동차결함 리콜현황" 파일데이터(2025-12-31 기준)를 근거로, 국산/수입 완성차
  // 제작사(현대/기아/제네시스/쉐보레/르노코리아/KG모빌리티) 소속 2025년 리콜 차종을
  // 폭넓게 추가한 항목입니다. 같은 리콜사유·리콜개시일을 공유하는 트림들은 하나의
  // 리콜로 묶었고, 생산기간(부터/까지)에 걸친 연도를 applicableYears로 반영했습니다.
  {
    id: "r-tivoli-20250110",
    vehicleSlugs: ["kgmobility/tivoli"],
    manufacturer: "KG모빌리티",
    affectedModelsText: "티볼리(G15)",
    title: "티볼리/코란도(G15) 일부 차량이 냉각팬 레지스터(저항 코일에 지속/반복적인 열… 관련 리콜",
    recallDate: "2025-01-10",
    productionStart: "2019-05",
    productionEnd: "2025-01",
    applicableYears: [2019, 2020, 2021, 2022, 2023, 2024, 2025],
    defect: "티볼리/코란도(G15) 일부 차량이 냉각팬 레지스터(저항 코일에 지속/반복적인 열적 부하 발생으로 인해 코일이 과열된 상태에서 원인불상으로 인한 주정차 시 화재 발생 가능성",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-korando-20250110",
    vehicleSlugs: ["kgmobility/korando"],
    manufacturer: "KG모빌리티",
    affectedModelsText: "코란도(G15)",
    title: "티볼리/코란도(G15) 일부 차량이 냉각팬 레지스터(저항 코일에 지속/반복적인 열… 관련 리콜",
    recallDate: "2025-01-10",
    productionStart: "2019-07",
    productionEnd: "2025-01",
    applicableYears: [2019, 2020, 2021, 2022, 2023, 2024, 2025],
    defect: "티볼리/코란도(G15) 일부 차량이 냉각팬 레지스터(저항 코일에 지속/반복적인 열적 부하 발생으로 인해 코일이 과열된 상태에서 원인불상으로 인한 주정차 시 화재 발생 가능성",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-ev9-20250122",
    vehicleSlugs: ["kia/ev9"],
    manufacturer: "기아",
    affectedModelsText: "EV9(MV)",
    title: "신규 작업자 시트 마운팅 볼트 체결 작업 미흡으로 시트 마운팅 볼트가 누락되어 시… 관련 리콜",
    recallDate: "2025-01-22",
    productionStart: "2023-05",
    productionEnd: "2024-06",
    applicableYears: [2023, 2024],
    defect: "신규 작업자 시트 마운팅 볼트 체결 작업 미흡으로 시트 마운팅 볼트가 누락되어 시트가 고정되지 않아 차량 충돌 발생 시 시트가 비정상 거동되어 안전에 지장을 줄 가능성",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-nexo-20250123",
    vehicleSlugs: ["hyundai/nexo"],
    manufacturer: "현대",
    affectedModelsText: "넥쏘(FE)",
    title: "일부 차량에서 비상점멸표시등(이하 비상등) 스위치의 내구 설계 오류로 비상등 스위… 관련 리콜",
    recallDate: "2025-01-23",
    productionStart: "2017-10",
    productionEnd: "2021-12",
    applicableYears: [2017, 2018, 2019, 2020, 2021],
    defect: "일부 차량에서 비상점멸표시등(이하 비상등) 스위치의 내구 설계 오류로 비상등 스위치를 작동시켜도 간헐적으로 비상등이 켜지지 않아 사고가 발생할 가능성이 있는 결함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-bongo3-20250131",
    vehicleSlugs: ["kia/bongo3"],
    manufacturer: "기아",
    affectedModelsText: "봉고Ⅲ (PU), 봉고Ⅲ EV(PU EV)",
    title: "12V 배터리 센서 설계 불량으로 인해 배터리 센서 소손 발생하여 안전 운행에 지… 관련 리콜",
    recallDate: "2025-01-31",
    productionStart: "2020-01",
    productionEnd: "2024-10",
    applicableYears: [2020, 2021, 2022, 2023, 2024],
    defect: "12V 배터리 센서 설계 불량으로 인해 배터리 센서 소손 발생하여 안전 운행에 지장을 줄 가능성",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-porter-20250203",
    vehicleSlugs: ["hyundai/porter"],
    manufacturer: "현대",
    affectedModelsText: "포터II EV",
    title: "포터II(HR) (LPDi, EV) 일부 차량에서 12v 배터리 센서 설계 불량으… 관련 리콜",
    recallDate: "2025-02-03",
    productionStart: "2019-07",
    productionEnd: "2024-09",
    applicableYears: [2019, 2020, 2021, 2022, 2023, 2024],
    defect: "포터II(HR) (LPDi, EV) 일부 차량에서 12v 배터리 센서 설계 불량으로 인해 배터리 센서에 수분이 유입되어 내부 회로 쇼트(단락)되는 경우 배터리 센서 소손 발생하여 안전 운행에 지장을 줄 가능성이 있는 결함이 확인 ※ 배터리 센서 : 배터리 상태(전압, 전류, 온도, 수명 등)를 파악하여 발전기가 효율적으로 작동하게 하는 부품",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-xm3-20250220",
    vehicleSlugs: ["renault/xm3"],
    manufacturer: "르노코리아",
    affectedModelsText: "XM3 하이브리드",
    title: "HEVC 및 DC/DC 컨버터의 소프트웨어 로직 미흡으로 인하여 구동 전기모터의 … 관련 리콜",
    recallDate: "2025-02-20",
    productionStart: "2022-09",
    productionEnd: "2024-03",
    applicableYears: [2022, 2023, 2024],
    defect: "HEVC 및 DC/DC 컨버터의 소프트웨어 로직 미흡으로 인하여 구동 전기모터의 전원이 차단되거나 저전압 배터리가 충전불가한 상황이 발생할 가능성이 있음",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-arkana-20250220",
    vehicleSlugs: ["renault/arkana"],
    manufacturer: "르노코리아",
    affectedModelsText: "ARKANA 하이브리드",
    title: "HEVC 및 DC/DC 컨버터의 소프트웨어 로직 미흡으로 인하여 구동 전기모터의 … 관련 리콜",
    recallDate: "2025-02-20",
    productionStart: "2024-04",
    productionEnd: "2024-12",
    applicableYears: [2024],
    defect: "HEVC 및 DC/DC 컨버터의 소프트웨어 로직 미흡으로 인하여 구동 전기모터의 전원이 차단되거나 저전압 배터리가 충전불가한 상황이 발생할 가능성이 있음",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-niro-20250226",
    vehicleSlugs: ["kia/niro"],
    manufacturer: "기아",
    affectedModelsText: "니로 (SG2 HEV)",
    title: "전기배선 경로 설계 불량으로 인해 전기배선이 승객감지장치에 간섭되어 전기배선이 손… 관련 리콜",
    recallDate: "2025-02-26",
    productionStart: "2021-12",
    productionEnd: "2025-01",
    applicableYears: [2021, 2022, 2023, 2024, 2025],
    defect: "전기배선 경로 설계 불량으로 인해 전기배선이 승객감지장치에 간섭되어 전기배선이 손상되는 경우 충돌 시 동승석 에어백(정면/측면)이 전개되지 않거나 비정상 전개될 수 있고 에어백 미전개 조건에서 동승석 측면 에어백이 자발 전개되어 탑승자 상해 발생 가능성",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-niroev-20250226",
    vehicleSlugs: ["kia/niro-ev"],
    manufacturer: "기아",
    affectedModelsText: "니로 EV (SG2 EV)",
    title: "전기배선 경로 설계 불량으로 인해 전기배선이 승객감지장치에 간섭되어 전기배선이 손… 관련 리콜",
    recallDate: "2025-02-26",
    productionStart: "2022-06",
    productionEnd: "2024-07",
    applicableYears: [2022, 2023, 2024],
    defect: "전기배선 경로 설계 불량으로 인해 전기배선이 승객감지장치에 간섭되어 전기배선이 손상되는 경우 충돌 시 동승석 에어백(정면/측면)이 전개되지 않거나 비정상 전개될 수 있고 에어백 미전개 조건에서 동승석 측면 에어백이 자발 전개되어 탑승자 상해 발생 가능성",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-g80-20250320",
    vehicleSlugs: ["genesis/g80"],
    manufacturer: "제네시스",
    affectedModelsText: "G80(RG3)",
    title: "G80(RG3), GV80(JX), GV70(JK), GV70 EV(JK EV) … 관련 리콜",
    recallDate: "2025-03-20",
    productionStart: "2022-12",
    productionEnd: "2024-01",
    applicableYears: [2022, 2023, 2024],
    defect: "G80(RG3), GV80(JX), GV70(JK), GV70 EV(JK EV) 일부 차량에서 계기판(8인치 계기판 적용 차량) 제어기 소프트웨어 설계 오류로 인해 초기 시동 시 간헐적으로 계기판 이미지가 표출되지 않아 ‘자동차 및 자동차 부품의 성능과 기준에 관한 규칙 제13조, 별표 2의 각주 9’ 안전기준에 적합하지 않는 사항이 확인되어 제작결함시정을 하고자 함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-gv70-20250320",
    vehicleSlugs: ["genesis/gv70"],
    manufacturer: "제네시스",
    affectedModelsText: "GV70(JK)",
    title: "G80(RG3), GV80(JX), GV70(JK), GV70 EV(JK EV) … 관련 리콜",
    recallDate: "2025-03-20",
    productionStart: "2024-03",
    productionEnd: "2024-06",
    applicableYears: [2024],
    defect: "G80(RG3), GV80(JX), GV70(JK), GV70 EV(JK EV) 일부 차량에서 계기판(8인치 계기판 적용 차량) 제어기 소프트웨어 설계 오류로 인해 초기 시동 시 간헐적으로 계기판 이미지가 표출되지 않아 ‘자동차 및 자동차 부품의 성능과 기준에 관한 규칙 제13조, 별표 2의 각주 9’ 안전기준에 적합하지 않는 사항이 확인되어 제작결함시정을 하고자 함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-gv70ev-20250320",
    vehicleSlugs: ["genesis/gv70-ev"],
    manufacturer: "제네시스",
    affectedModelsText: "GV70 EV(JK EV)",
    title: "G80(RG3), GV80(JX), GV70(JK), GV70 EV(JK EV) … 관련 리콜",
    recallDate: "2025-03-20",
    productionStart: "2023-02",
    productionEnd: "2024-12",
    applicableYears: [2023, 2024],
    defect: "G80(RG3), GV80(JX), GV70(JK), GV70 EV(JK EV) 일부 차량에서 계기판(8인치 계기판 적용 차량) 제어기 소프트웨어 설계 오류로 인해 초기 시동 시 간헐적으로 계기판 이미지가 표출되지 않아 ‘자동차 및 자동차 부품의 성능과 기준에 관한 규칙 제13조, 별표 2의 각주 9’ 안전기준에 적합하지 않는 사항이 확인되어 제작결함시정을 하고자 함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-countyelectric-20250320",
    vehicleSlugs: ["hyundai/county-electric"],
    manufacturer: "현대",
    affectedModelsText: "카운티 일렉트릭",
    title: "일부 차량에서 구동전동기 최고출력 설정 소프트웨어 로직 오적용으로 인해 구동전동기… 관련 리콜",
    recallDate: "2025-03-20",
    productionStart: "2020-05",
    productionEnd: "2025-03",
    applicableYears: [2020, 2021, 2022, 2023, 2024, 2025],
    defect: "일부 차량에서 구동전동기 최고출력 설정 소프트웨어 로직 오적용으로 인해 구동전동기 최고 출력에 대한 제원과 상이함.",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-ioniq5n-20250409",
    vehicleSlugs: ["hyundai/ioniq5-n"],
    manufacturer: "현대",
    affectedModelsText: "아이오닉5 N(NE N)",
    title: "일부 차량에서 레이싱 목적의 주행을 위한 특이모드인 양발운전모드(LFB)의 로직 … 관련 리콜",
    recallDate: "2025-04-09",
    productionStart: "2023-03",
    productionEnd: "2024-09",
    applicableYears: [2023, 2024],
    defect: "일부 차량에서 레이싱 목적의 주행을 위한 특이모드인 양발운전모드(LFB)의 로직 설계오류로 일부 작동조건에 따라 의도치 않게 제동거리의 증가가 발생하여 안전 운행에 지장을 줄 가능성이 있는 결함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-camaro-20250421",
    vehicleSlugs: ["chevrolet/camaro"],
    manufacturer: "쉐보레",
    affectedModelsText: "카마로",
    title: "토크 센서 커넥터 핀이 PCB(회로기판)에 조립될 때 잘 못된 방향으로 조립되어 … 관련 리콜",
    recallDate: "2025-04-21",
    productionStart: "2016-11",
    productionEnd: "2016-11",
    applicableYears: [2016],
    defect: "토크 센서 커넥터 핀이 PCB(회로기판)에 조립될 때 잘 못된 방향으로 조립되어 차량의 진동 등에 의해 커넥터 핀이 휘어져 접촉 불량이 발생할 가능성이 있고, 이로 인해 전동식 조향장치 내부의 토크 센서 커넥터가 간헐적인 접촉 불량으로 주행 중 조향 시 구동모터의 기능이 상실될 가능성이 있음.",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-gv70-20250424",
    vehicleSlugs: ["genesis/gv70"],
    manufacturer: "제네시스",
    affectedModelsText: "GV70 (JK1 PE)",
    title: "GV70(JK1 PE), GV70 Electrified(JK1 EV PE), 아이… 관련 리콜",
    recallDate: "2025-04-24",
    productionStart: "2024-12",
    productionEnd: "2025-03",
    applicableYears: [2024, 2025],
    defect: "GV70(JK1 PE), GV70 Electrified(JK1 EV PE), 아이오닉9(ME1) 일부 차량에서 에어백 제어장치(ACU) 소프트웨어 설계 오류로 차량 시동시 에어백 제어장치(ACU) 프로그램 구동 오류가 발생하여 에어백 경고등 점등과 에어백이 미전개되며 안전운행에 지장을 줄 가능성이 있는 결함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-gv70ev-20250424",
    vehicleSlugs: ["genesis/gv70-ev"],
    manufacturer: "제네시스",
    affectedModelsText: "GV70 Electrified (JK1 EV PE)",
    title: "GV70(JK1 PE), GV70 Electrified(JK1 EV PE), 아이… 관련 리콜",
    recallDate: "2025-04-24",
    productionStart: "2024-12",
    productionEnd: "2025-04",
    applicableYears: [2024, 2025],
    defect: "GV70(JK1 PE), GV70 Electrified(JK1 EV PE), 아이오닉9(ME1) 일부 차량에서 에어백 제어장치(ACU) 소프트웨어 설계 오류로 차량 시동시 에어백 제어장치(ACU) 프로그램 구동 오류가 발생하여 에어백 경고등 점등과 에어백이 미전개되며 안전운행에 지장을 줄 가능성이 있는 결함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-ioniq9-20250424",
    vehicleSlugs: ["hyundai/ioniq9"],
    manufacturer: "현대",
    affectedModelsText: "아이오닉9(ME1)",
    title: "GV70(JK1 PE), GV70 Electrified(JK1 EV PE), 아이… 관련 리콜",
    recallDate: "2025-04-24",
    productionStart: "2024-12",
    productionEnd: "2025-03",
    applicableYears: [2024, 2025],
    defect: "GV70(JK1 PE), GV70 Electrified(JK1 EV PE), 아이오닉9(ME1) 일부 차량에서 에어백 제어장치(ACU) 소프트웨어 설계 오류로 차량 시동시 에어백 제어장치(ACU) 프로그램 구동 오류가 발생하여 에어백 경고등 점등과 에어백이 미전개되며 안전운행에 지장을 줄 가능성이 있는 결함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-eleccityfcev-20250522",
    vehicleSlugs: ["hyundai/elec-city-fcev"],
    manufacturer: "현대",
    affectedModelsText: "일렉시티(CY) 수소전기버스",
    title: "일렉시티(CY) 수소전기버스 일부 차량에서 수소 배출구 보호마개를 통한 수분유입 … 관련 리콜",
    recallDate: "2025-05-22",
    productionStart: "2019-05",
    productionEnd: "2025-03",
    applicableYears: [2019, 2020, 2021, 2022, 2023, 2024, 2025],
    defect: "일렉시티(CY) 수소전기버스 일부 차량에서 수소 배출구 보호마개를 통한 수분유입 및 빙결이 발생되어 수소가 배출되지 못할 시 중압 배관 연결부가 이탈되어 수소가 누출될 가능성이 있는 결함이 확인 ※ 수소 배출구 보호마개 : 수소 감압기의 토출압이 과다할 경우 수소를 배출시키는 마개",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-traverse-20250523",
    vehicleSlugs: ["chevrolet/traverse"],
    manufacturer: "쉐보레",
    affectedModelsText: "트래버스",
    title: "현상 : 후부 및 옆면 반사기의 반사 성능이 안전 기준을 충족하지 못할 가능성이 … 관련 리콜",
    recallDate: "2025-05-23",
    productionStart: "2016-11",
    productionEnd: "2019-01",
    applicableYears: [2016, 2017, 2018, 2019],
    defect: "현상 : 후부 및 옆면 반사기의 반사 성능이 안전 기준을 충족하지 못할 가능성이 있음. 원인 : 현재까지 근본 원인은 파악 중에 있으나, 정확한 원인을 규명하는 데에는 한계가 있음. 그러나, 국내로 수입, 판매된 반사기의 한정된 부품 품질 편차가 반사 성능 저하에 영향을 주었을 것으로 추정됨. * 2024년 4월부터 반사기 부품업체의 생산품질 강화 및 개선사항이 적용된 부품이 국내로 공급되고 있음.",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-seltos-20250528",
    vehicleSlugs: ["kia/seltos"],
    manufacturer: "기아",
    affectedModelsText: "셀토스 (SP2)",
    title: "고압 파이프 제조 불량으로 인해 연결부 기밀성이 저하되어 연료가 누유되는 경우 차… 관련 리콜",
    recallDate: "2025-05-28",
    productionStart: "2024-10",
    productionEnd: "2024-12",
    applicableYears: [2024],
    defect: "고압 파이프 제조 불량으로 인해 연결부 기밀성이 저하되어 연료가 누유되는 경우 차량 화재 발생 가능성",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-sportage-20250528",
    vehicleSlugs: ["kia/sportage"],
    manufacturer: "기아",
    affectedModelsText: "스포티지 (NQ5)",
    title: "고압 파이프 제조 불량으로 인해 연결부 기밀성이 저하되어 연료가 누유되는 경우 차… 관련 리콜",
    recallDate: "2025-05-28",
    productionStart: "2024-10",
    productionEnd: "2024-12",
    applicableYears: [2024],
    defect: "고압 파이프 제조 불량으로 인해 연결부 기밀성이 저하되어 연료가 누유되는 경우 차량 화재 발생 가능성",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-i30-20250610",
    vehicleSlugs: ["hyundai/i30"],
    manufacturer: "현대",
    affectedModelsText: "i30(FD)",
    title: "아반떼(HD) 등 2차종 일부 차량에서 운전석 에어백 전개시 인플레이터의 과도한 … 관련 리콜",
    recallDate: "2025-06-10",
    productionStart: "2008-10",
    productionEnd: "2009-02",
    applicableYears: [2008, 2009],
    defect: "아반떼(HD) 등 2차종 일부 차량에서 운전석 에어백 전개시 인플레이터의 과도한 내부 압력 증가로 인해 인플레이터 용기가 파손되어 승객이 상해를 입을 가능성이 있는 결함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-countyelectric-20250619",
    vehicleSlugs: ["hyundai/county-electric"],
    manufacturer: "현대",
    affectedModelsText: "카운티 일렉트릭(CS EV)",
    title: "카운티 일렉트릭(CS EV) 일부 차량에서 주차브레이크 하중전달용 케이블 설계 오… 관련 리콜",
    recallDate: "2025-06-19",
    productionStart: "2020-05",
    productionEnd: "2025-06",
    applicableYears: [2020, 2021, 2022, 2023, 2024, 2025],
    defect: "카운티 일렉트릭(CS EV) 일부 차량에서 주차브레이크 하중전달용 케이블 설계 오류로 이물질 유입으로 인해 주차브레이크 하중전달용 케이블이 절손되어 경사로 주차 시 차량 밀림으로 충돌사고 발생 가능성이 있는 결함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-k3-20250623",
    vehicleSlugs: ["kia/k3"],
    manufacturer: "기아",
    affectedModelsText: "포르테 (TD)",
    title: "조수석 에어백 인플레이터 용기 제조 공정 불량으로 인해 저온조건에서 에어백 전개 … 관련 리콜",
    recallDate: "2025-06-23",
    productionStart: "2008-11",
    productionEnd: "2012-11",
    applicableYears: [2008, 2009, 2010, 2011, 2012],
    defect: "조수석 에어백 인플레이터 용기 제조 공정 불량으로 인해 저온조건에서 에어백 전개 시 인플레이터 용기가 파열되어 탑승자에게 상해를 입힐 가능성",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-camaro-20250627",
    vehicleSlugs: ["chevrolet/camaro"],
    manufacturer: "쉐보레",
    affectedModelsText: "카마로",
    title: "자동변속기 유압 제어 장치 내부가 시간이 지남에 따라 마모된 경우 오일 누유로 인… 관련 리콜",
    recallDate: "2025-06-27",
    productionStart: "2019-08",
    productionEnd: "2021-05",
    applicableYears: [2019, 2020, 2021],
    defect: "자동변속기 유압 제어 장치 내부가 시간이 지남에 따라 마모된 경우 오일 누유로 인한 압력 저하로 밸브가 의도하지 않게 오작동하여 주행 중 변속 충격 및 드물게 순간적인 바퀴잠김 현상이 발생할 가능성이 있음.",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-casperelectric-20250710",
    vehicleSlugs: ["hyundai/casper-electric"],
    manufacturer: "현대",
    affectedModelsText: "캐스퍼 일렉트릭 (AX1 EV)",
    title: "캐스퍼 일렉트릭(AX1 EV) 일부 차량에서 조수석 하단 운전자 보조 주차 제어기… 관련 리콜",
    recallDate: "2025-07-10",
    productionStart: "2024-07",
    productionEnd: "2025-03",
    applicableYears: [2024, 2025],
    defect: "캐스퍼 일렉트릭(AX1 EV) 일부 차량에서 조수석 하단 운전자 보조 주차 제어기(ADAS PRK ECU) 조립용 차체부 볼트가 노출되어 뒷좌석 승객이 맨발로 탑승시 상해가 발생할 가능성이 있는 결함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-staria-20250731",
    vehicleSlugs: ["hyundai/staria"],
    manufacturer: "현대",
    affectedModelsText: "스타리아 카고 (US4)",
    title: "스타리아 카고(US4), 쏠라티(EU) 일부 차량에서 휠 고정용 너트 체결 작업 … 관련 리콜",
    recallDate: "2025-07-31",
    productionStart: "2022-12",
    productionEnd: "2025-04",
    applicableYears: [2022, 2023, 2024, 2025],
    defect: "스타리아 카고(US4), 쏠라티(EU) 일부 차량에서 휠 고정용 너트 체결 작업 불량으로 주행 중 너트 풀림에 의한 휠 이탈 발생 가능성이 있는 결함 사항 확인",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-solati-20250731",
    vehicleSlugs: ["hyundai/solati"],
    manufacturer: "현대",
    affectedModelsText: "쏠라티 (EU)",
    title: "스타리아 카고(US4), 쏠라티(EU) 일부 차량에서 휠 고정용 너트 체결 작업 … 관련 리콜",
    recallDate: "2025-07-31",
    productionStart: "2015-09",
    productionEnd: "2025-04",
    applicableYears: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025],
    defect: "스타리아 카고(US4), 쏠라티(EU) 일부 차량에서 휠 고정용 너트 체결 작업 불량으로 주행 중 너트 풀림에 의한 휠 이탈 발생 가능성이 있는 결함 사항 확인",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-sm6-20250811",
    vehicleSlugs: ["renault/sm6"],
    manufacturer: "르노코리아",
    affectedModelsText: "SM6",
    title: "일부 차량에 장착된 진공펌프 내 체크밸브를 고정하는 스크류가 체결되는 하우징의 나… 관련 리콜",
    recallDate: "2025-08-11",
    productionStart: "2023-02",
    productionEnd: "2023-04",
    applicableYears: [2023],
    defect: "일부 차량에 장착된 진공펌프 내 체크밸브를 고정하는 스크류가 체결되는 하우징의 나사산 가공 불량으로, 스크류가 이탈되어 진공압이 부족할 가능성이 있음",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-xm3-20250811",
    vehicleSlugs: ["renault/xm3"],
    manufacturer: "르노코리아",
    affectedModelsText: "XM3",
    title: "일부 차량에 장착된 진공펌프 내 체크밸브를 고정하는 스크류가 체결되는 하우징의 나… 관련 리콜",
    recallDate: "2025-08-11",
    productionStart: "2023-01",
    productionEnd: "2023-05",
    applicableYears: [2023],
    defect: "일부 차량에 장착된 진공펌프 내 체크밸브를 고정하는 스크류가 체결되는 하우징의 나사산 가공 불량으로, 스크류가 이탈되어 진공압이 부족할 가능성이 있음",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-tahoe-20250813",
    vehicleSlugs: ["chevrolet/tahoe"],
    manufacturer: "쉐보레",
    affectedModelsText: "타호",
    title: "엔진의 일부 부품의 제조 품질 문제로 인해 엔진 베어링의 이상 마모가 발생하여 엔… 관련 리콜",
    recallDate: "2025-08-13",
    productionStart: "2021-06",
    productionEnd: "2022-11",
    applicableYears: [2021, 2022],
    defect: "엔진의 일부 부품의 제조 품질 문제로 인해 엔진 베어링의 이상 마모가 발생하여 엔진을 손상시킬 가능성을 확인하였고, 이로 인해 주행 중 추진력 상실 및 시동꺼짐 현상이 발생할 가능성이 있음. 엔진 분해 분석 결과 이는 아래 두 가지 제조 품질 원인에 기인함. 1) 커넥팅 로드의 제조 공정상 발생한 이물질에 의한 엔진 베어링 손상 2) 크랭크 샤프트의 제조 품질 문제 (치수 및 표면 마무리)",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-sierra-20250813",
    vehicleSlugs: ["chevrolet/sierra"],
    manufacturer: "쉐보레",
    affectedModelsText: "시에라",
    title: "엔진의 일부 부품의 제조 품질 문제로 인해 엔진 베어링의 이상 마모가 발생하여 엔… 관련 리콜",
    recallDate: "2025-08-13",
    productionStart: "2022-06",
    productionEnd: "2024-05",
    applicableYears: [2022, 2023, 2024],
    defect: "엔진의 일부 부품의 제조 품질 문제로 인해 엔진 베어링의 이상 마모가 발생하여 엔진을 손상시킬 가능성을 확인하였고, 이로 인해 주행 중 추진력 상실 및 시동꺼짐 현상이 발생할 가능성이 있음. 엔진 분해 분석 결과 이는 아래 두 가지 제조 품질 원인에 기인함. 1) 커넥팅 로드의 제조 공정상 발생한 이물질에 의한 엔진 베어링 손상 2) 크랭크 샤프트의 제조 품질 문제 (치수 및 표면 마무리)",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-porter-20250905",
    vehicleSlugs: ["hyundai/porter"],
    manufacturer: "현대",
    affectedModelsText: "포터II 일렉트릭(HR EV)",
    title: "일부 차량에서 고전압배터리 케이스 사후관리용 부품 불량으로 인해 프로펠러 샤프트와… 관련 리콜",
    recallDate: "2025-09-05",
    productionStart: "2022-06",
    productionEnd: "2024-02",
    applicableYears: [2022, 2023, 2024],
    defect: "일부 차량에서 고전압배터리 케이스 사후관리용 부품 불량으로 인해 프로펠러 샤프트와 케이스 간의 간섭 부위가 절삭되지 않은 부품이 장착되어, 프로펠러 샤프트에 충격 피로 누적 시 파손 및 동력 전달 불가로 차량 멈춤 가능성이 있는 결함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-ev3-20250924",
    vehicleSlugs: ["kia/ev3"],
    manufacturer: "기아",
    affectedModelsText: "EV3",
    title: "기아㈜에서는 EV3(SV), EV4(CT) 일부 차량에서 차량 내부 A필러(LH)… 관련 리콜",
    recallDate: "2025-09-24",
    productionStart: "2025-07",
    productionEnd: "2025-07",
    applicableYears: [2025],
    defect: "기아㈜에서는 EV3(SV), EV4(CT) 일부 차량에서 차량 내부 A필러(LH) 트림 테더클립 미체결로 인한 들뜸으로 커튼 에어백 전개 시 A필러(LH) 트림이 이탈되어 고객 상해 발생 가능성이 있는 결함이 확인되어 제작결함시정을 하고자 함 (결함인지일 : ‘25. 8. 29) ※ 테더클립 : 커튼에어백 전개 시 A필러 트림이 완전히 이탈되지 않고 적당히 열리면서 커튼 에어백만 전개 될 수 있도록 하는 장치",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-ev4-20250924",
    vehicleSlugs: ["kia/ev4"],
    manufacturer: "기아",
    affectedModelsText: "EV4",
    title: "기아㈜에서는 EV3(SV), EV4(CT) 일부 차량에서 차량 내부 A필러(LH)… 관련 리콜",
    recallDate: "2025-09-24",
    productionStart: "2025-07",
    productionEnd: "2025-07",
    applicableYears: [2025],
    defect: "기아㈜에서는 EV3(SV), EV4(CT) 일부 차량에서 차량 내부 A필러(LH) 트림 테더클립 미체결로 인한 들뜸으로 커튼 에어백 전개 시 A필러(LH) 트림이 이탈되어 고객 상해 발생 가능성이 있는 결함이 확인되어 제작결함시정을 하고자 함 (결함인지일 : ‘25. 8. 29) ※ 테더클립 : 커튼에어백 전개 시 A필러 트림이 완전히 이탈되지 않고 적당히 열리면서 커튼 에어백만 전개 될 수 있도록 하는 장치",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-xm3-20250925",
    vehicleSlugs: ["renault/xm3"],
    manufacturer: "르노코리아",
    affectedModelsText: "XM3 하이브리드",
    title: "모터만 작동하는 EV 모드에서 엔진이 구동하는 모드로 변환 시, 특정 조건에서 연… 관련 리콜",
    recallDate: "2025-09-25",
    productionStart: "2022-09",
    productionEnd: "2024-03",
    applicableYears: [2022, 2023, 2024],
    defect: "모터만 작동하는 EV 모드에서 엔진이 구동하는 모드로 변환 시, 특정 조건에서 연료 펌프에 공급되는 전원이 차단/공급되는 로직으로 인해 연료 펌프 컨트롤 유닛의 커패시터의 열화가 발생할 가능성이 있음",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-arkana-20250925",
    vehicleSlugs: ["renault/arkana"],
    manufacturer: "르노코리아",
    affectedModelsText: "ARKANA 하이브리드",
    title: "모터만 작동하는 EV 모드에서 엔진이 구동하는 모드로 변환 시, 특정 조건에서 연… 관련 리콜",
    recallDate: "2025-09-25",
    productionStart: "2024-04",
    productionEnd: "2025-06",
    applicableYears: [2024, 2025],
    defect: "모터만 작동하는 EV 모드에서 엔진이 구동하는 모드로 변환 시, 특정 조건에서 연료 펌프에 공급되는 전원이 차단/공급되는 로직으로 인해 연료 펌프 컨트롤 유닛의 커패시터의 열화가 발생할 가능성이 있음",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-porter-20250925",
    vehicleSlugs: ["hyundai/porter"],
    manufacturer: "현대",
    affectedModelsText: "포터2(HR)",
    title: "포터2(HR) LPG 엔진 일부 차량에서 장력조절장치(텐셔너) 고정볼트 체결부 형… 관련 리콜",
    recallDate: "2025-09-25",
    productionStart: "2023-11",
    productionEnd: "2025-03",
    applicableYears: [2023, 2024, 2025],
    defect: "포터2(HR) LPG 엔진 일부 차량에서 장력조절장치(텐셔너) 고정볼트 체결부 형상 설계 불량으로 인해 고정볼트가 풀려 구동벨트가 이탈되는 경우 파워스티어링 펌프 작동불량에 의해 핸들 조향이 정상적으로 되지 않아 안전에 지장을 줄 가능성이 있는 결함이 확인되어 제작결함 시정을 하고자 함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-bongo3-20250925",
    vehicleSlugs: ["kia/bongo3"],
    manufacturer: "기아",
    affectedModelsText: "봉고Ⅲ (PU)",
    title: "봉고Ⅲ (PU) LPG 엔진 일부 차량에서 장력조절장치(텐셔너) 체결부 형상 설계… 관련 리콜",
    recallDate: "2025-09-25",
    productionStart: "2023-12",
    productionEnd: "2025-02",
    applicableYears: [2023, 2024, 2025],
    defect: "봉고Ⅲ (PU) LPG 엔진 일부 차량에서 장력조절장치(텐셔너) 체결부 형상 설계 불량으로 인해 고정볼트가 풀려 구동벨트가 이탈되는 경우 파워스티어링 펌프 작동불량에 의해 핸들 조향이 정상적으로 되지 않아 안전에 지장을 줄 가능성",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-i30-20250926",
    vehicleSlugs: ["hyundai/i30"],
    manufacturer: "현대",
    affectedModelsText: "i30(FD)",
    title: "30(FD) 일부 차량에서 운전석 에어백 인플레이터의 과도한 내부 압력 증가로 인… 관련 리콜",
    recallDate: "2025-09-26",
    productionStart: "2011-04",
    productionEnd: "2011-06",
    applicableYears: [2011],
    defect: "30(FD) 일부 차량에서 운전석 에어백 인플레이터의 과도한 내부 압력 증가로 인해 인플레이터 용기가 파손되어 승객이 상해를 입을 가능성이 있는 결함이 발견됨",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-pavise-20250926",
    vehicleSlugs: ["hyundai/pavise"],
    manufacturer: "현대",
    affectedModelsText: "파비스 (QV)",
    title: "파비스 (QV) 일부 차량에서 엔진제어장치(ECU) 소프트웨어 오적용으로 인해엔진… 관련 리콜",
    recallDate: "2025-09-26",
    productionStart: "2025-02",
    productionEnd: "2025-08",
    applicableYears: [2025],
    defect: "파비스 (QV) 일부 차량에서 엔진제어장치(ECU) 소프트웨어 오적용으로 인해엔진 최고 출력이 제원과 상이하여 ‘자동차 및 자동차 부품의 성능과 기준에 관한 규칙 제106조(원동기 출력) 1호’ 안전기준에 적합하지 않은 결함이 발견됨",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-mussoev-20251015",
    vehicleSlugs: ["kgmobility/musso-ev"],
    manufacturer: "KG모빌리티",
    affectedModelsText: "무쏘 EV",
    title: "고전압은 정상적으로 인가되나 간헐적으로 고전압 시스템 내 이상 신호가 진단될 경우… 관련 리콜",
    recallDate: "2025-10-15",
    productionStart: "2025-02",
    productionEnd: "2025-09",
    applicableYears: [2025],
    defect: "고전압은 정상적으로 인가되나 간헐적으로 고전압 시스템 내 이상 신호가 진단될 경우, 고전압이 차단되어 경고등 점등 및 지속 주행 시 시동 꺼짐 현상 발생",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-gv60-20251022",
    vehicleSlugs: ["genesis/gv60"],
    manufacturer: "제네시스",
    affectedModelsText: "GV60(JW)",
    title: "현대자동차㈜에서는 GV60(JW) 일부 차량에서 앞면창유리 상단 몰딩 제조 불량으… 관련 리콜",
    recallDate: "2025-10-22",
    productionStart: "2021-10",
    productionEnd: "2024-07",
    applicableYears: [2021, 2022, 2023, 2024],
    defect: "현대자동차㈜에서는 GV60(JW) 일부 차량에서 앞면창유리 상단 몰딩 제조 불량으로 인해 접착력이 저하되어 주행 중 앞면창유리 상단 몰딩 본체에서 표면부가 이탈하여 사고를 초래할 가능성이 있는 결함이 발견되어 제작결함시정을 하고자 함.",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-ioniq6-20251024",
    vehicleSlugs: ["hyundai/ioniq6"],
    manufacturer: "현대",
    affectedModelsText: "아이오닉6(CE)",
    title: "아이오닉6(CE) 일부 차량에서 충전도어 외부 커버 설계 미흡으로 인해 체결력이 … 관련 리콜",
    recallDate: "2025-10-24",
    productionStart: "2022-08",
    productionEnd: "2024-10",
    applicableYears: [2022, 2023, 2024],
    defect: "아이오닉6(CE) 일부 차량에서 충전도어 외부 커버 설계 미흡으로 인해 체결력이 부족하여, 주행 중 부품 이탈로 인한 사고 발생 가능성이 있는 결함이 발견됨",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-kona-20251029",
    vehicleSlugs: ["hyundai/kona"],
    manufacturer: "현대",
    affectedModelsText: "코나(OS)",
    title: "현대자동차㈜에서는 코나(OS), 투싼(TL) 디젤 1.6 엔진 장착 일부 차량에서… 관련 리콜",
    recallDate: "2025-10-29",
    productionStart: "2018-03",
    productionEnd: "2020-08",
    applicableYears: [2018, 2019, 2020],
    defect: "현대자동차㈜에서는 코나(OS), 투싼(TL) 디젤 1.6 엔진 장착 일부 차량에서 연료필터 설계오류(유리섬유 성분 사용)로 인해 여과지의 유리섬유 성분이 탈락되어 고압펌프로 유입되면 고압펌프의 내부 부품이 손상되어 연료분사가 정상적으로 작동되지 않아 시동이 꺼질 가능성이 있는 결함이 발견되어 (결함인지일 : ’22. 5. 10) ’22. 7. 11 부터 시정조치를 진행하였음 시정조치 이후 코나(OS), 투싼(TL) 디젤 1.6 엔진 장착 일부 차량에서 기 조치차량 및 조치 대상 외 차량에서 고압펌프 및 연료계 부품 내부 잔존 연료필터 유리섬유 등 이물로 인해 고압펌프 내부가 손상되어 연료분사가 정상적으로 작동되지 않아 주행중 시동이 꺼질 가능성이 있는 결함이 발견되어 제작결함시정을 하고자 함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-tucson-20251029",
    vehicleSlugs: ["hyundai/tucson"],
    manufacturer: "현대",
    affectedModelsText: "투싼(TL)",
    title: "현대자동차㈜에서는 코나(OS), 투싼(TL) 디젤 1.6 엔진 장착 일부 차량에서… 관련 리콜",
    recallDate: "2025-10-29",
    productionStart: "2018-01",
    productionEnd: "2020-09",
    applicableYears: [2018, 2019, 2020],
    defect: "현대자동차㈜에서는 코나(OS), 투싼(TL) 디젤 1.6 엔진 장착 일부 차량에서 연료필터 설계오류(유리섬유 성분 사용)로 인해 여과지의 유리섬유 성분이 탈락되어 고압펌프로 유입되면 고압펌프의 내부 부품이 손상되어 연료분사가 정상적으로 작동되지 않아 시동이 꺼질 가능성이 있는 결함이 발견되어 (결함인지일 : ’22. 5. 10) ’22. 7. 11 부터 시정조치를 진행하였음 시정조치 이후 코나(OS), 투싼(TL) 디젤 1.6 엔진 장착 일부 차량에서 기 조치차량 및 조치 대상 외 차량에서 고압펌프 및 연료계 부품 내부 잔존 연료필터 유리섬유 등 이물로 인해 고압펌프 내부가 손상되어 연료분사가 정상적으로 작동되지 않아 주행중 시동이 꺼질 가능성이 있는 결함이 발견되어 제작결함시정을 하고자 함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-seltos-20251029",
    vehicleSlugs: ["kia/seltos"],
    manufacturer: "기아",
    affectedModelsText: "셀토스 (SP2)",
    title: "기아㈜에서는 셀토스(SP2), 스포티지(QL) 디젤 1.6 엔진 장착 일부 차량에… 관련 리콜",
    recallDate: "2025-10-29",
    productionStart: "2019-07",
    productionEnd: "2021-12",
    applicableYears: [2019, 2020, 2021],
    defect: "기아㈜에서는 셀토스(SP2), 스포티지(QL) 디젤 1.6 엔진 장착 일부 차량에서 연료필터 설계오류(유리섬유 성분 사용)로 인해 여과지의 유리섬유 성분이 탈락되어 고압펌프로 유입되면 고압펌프의 내부 부품이 손상되어 연료분사가 정상적으로 작동되지 않아 시동이 꺼질 가능성이 있는 결함이 발견되어 (결함인지일 : ’22. 5. 10) ’22. 7. 11 부터 시정조치를 진행하였음 시정조치 이후 셀토스(SP2), 스포티지(QL) 디젤 1.6 엔진 장착 일부 차량에서 기 조치차량 및 조치 대상 외 차량에서 고압펌프 및 연료계 부품 내부 잔존 연료필터 유리섬유 등 이물로 인해 고압펌프 내부가 손상되어 연료분사가 정상적으로 작동되지 않아 주행중 시동이 꺼질 가능성이 있는 결함이 발견되어 제작결함시정을 하고자 함 (결함인지일 : ’25. 9. 30)",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-sportage-20251029",
    vehicleSlugs: ["kia/sportage"],
    manufacturer: "기아",
    affectedModelsText: "스포티지 (QL)",
    title: "기아㈜에서는 셀토스(SP2), 스포티지(QL) 디젤 1.6 엔진 장착 일부 차량에… 관련 리콜",
    recallDate: "2025-10-29",
    productionStart: "2018-06",
    productionEnd: "2021-07",
    applicableYears: [2018, 2019, 2020, 2021],
    defect: "기아㈜에서는 셀토스(SP2), 스포티지(QL) 디젤 1.6 엔진 장착 일부 차량에서 연료필터 설계오류(유리섬유 성분 사용)로 인해 여과지의 유리섬유 성분이 탈락되어 고압펌프로 유입되면 고압펌프의 내부 부품이 손상되어 연료분사가 정상적으로 작동되지 않아 시동이 꺼질 가능성이 있는 결함이 발견되어 (결함인지일 : ’22. 5. 10) ’22. 7. 11 부터 시정조치를 진행하였음 시정조치 이후 셀토스(SP2), 스포티지(QL) 디젤 1.6 엔진 장착 일부 차량에서 기 조치차량 및 조치 대상 외 차량에서 고압펌프 및 연료계 부품 내부 잔존 연료필터 유리섬유 등 이물로 인해 고압펌프 내부가 손상되어 연료분사가 정상적으로 작동되지 않아 주행중 시동이 꺼질 가능성이 있는 결함이 발견되어 제작결함시정을 하고자 함 (결함인지일 : ’25. 9. 30)",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-porter-20251030",
    vehicleSlugs: ["hyundai/porter"],
    manufacturer: "현대",
    affectedModelsText: "포터II 일렉트릭(HR EV)",
    title: "현대자동차㈜에서는 포터II 일렉트릭(HR EV) 일부 차량에서 배터리관리시스템(B… 관련 리콜",
    recallDate: "2025-10-30",
    productionStart: "2019-07",
    productionEnd: "2025-03",
    applicableYears: [2019, 2020, 2021, 2022, 2023, 2024, 2025],
    defect: "현대자동차㈜에서는 포터II 일렉트릭(HR EV) 일부 차량에서 배터리관리시스템(BMS) 진단로직 설계 미흡으로 배터리셀 미세 단락 등 문제 발생시 이를 사전에 감지하지 못해 고전압배터리 화재 발생 가능성",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-bongo3-20251030",
    vehicleSlugs: ["kia/bongo3"],
    manufacturer: "기아",
    affectedModelsText: "봉고Ⅲ 전기차(PUEV)",
    title: "봉고Ⅲ 전기차 (PU EV) 일부 차량에서 배터리관리시스템(BMS) 진단로직 설계… 관련 리콜",
    recallDate: "2025-10-30",
    productionStart: "2020-01",
    productionEnd: "2025-04",
    applicableYears: [2020, 2021, 2022, 2023, 2024, 2025],
    defect: "봉고Ⅲ 전기차 (PU EV) 일부 차량에서 배터리관리시스템(BMS) 진단로직 설계 미흡으로 배터리셀 미세 단락 등 문제 발생시 이를 사전에 감지하지 못해 고전압배터리 화재 발생 가능성",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-solati-20251114",
    vehicleSlugs: ["hyundai/solati"],
    manufacturer: "현대",
    affectedModelsText: "쏠라티(EU)",
    title: "쏠라티(EU) 일부 차량에서 조수석 에어백 인플레이터 용기의 제조불량으로 인해 저… 관련 리콜",
    recallDate: "2025-11-14",
    productionStart: "2023-02",
    productionEnd: "2025-03",
    applicableYears: [2023, 2024, 2025],
    defect: "쏠라티(EU) 일부 차량에서 조수석 에어백 인플레이터 용기의 제조불량으로 인해 저온조건에서 에어백 전개 시 인플레이터 용기가 파열되며 승객이 상해를 입을 가능성이 있는 결함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-staria-20251212",
    vehicleSlugs: ["hyundai/staria"],
    manufacturer: "현대",
    affectedModelsText: "스타리아 하이브리드 (US4 HEV)",
    title: "현대자동차㈜에서는 스타리아 하이브리드(US4 HEV) 일부 차량에서 하이브리드 통… 관련 리콜",
    recallDate: "2025-12-12",
    productionStart: "2024-02",
    productionEnd: "2025-08",
    applicableYears: [2024, 2025],
    defect: "현대자동차㈜에서는 스타리아 하이브리드(US4 HEV) 일부 차량에서 하이브리드 통합 제어기(HPCU) 소프트웨어 설계 오류로 동절기 원격시동 및 히터 작동 등 전장 고부하 시 하이브리드 통합 제어기(HPCU) 소손 발생 가능성이 있는 결함이 발견되어 제작결함시정을 하고자 함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-porter-20251219",
    vehicleSlugs: ["hyundai/porter"],
    manufacturer: "현대",
    affectedModelsText: "포터II(HR)",
    title: "일부 차량에서 변속 케이블 체결부 설계 오류로 인해 변속 케이블이 고정되지 않고 … 관련 리콜",
    recallDate: "2025-12-19",
    productionStart: "2024-02",
    productionEnd: "2025-06",
    applicableYears: [2024, 2025],
    defect: "일부 차량에서 변속 케이블 체결부 설계 오류로 인해 변속 케이블이 고정되지 않고 이탈되어 운전자의 의도와 상이한 변속 상태로 차량 움직임이 발생하여 사고가 발생할 가능성이 있는 결함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
];

export function getRecallsForVehicle(manufacturerSlug: string, slug: string) {
  const key = `${manufacturerSlug}/${slug}`;
  return recalls
    .filter((r) => r.vehicleSlugs.includes(key))
    .sort((a, b) => (a.recallDate < b.recallDate ? 1 : -1));
}

export function getRecallsForVehicleYear(
  manufacturerSlug: string,
  slug: string,
  year: number
) {
  return getRecallsForVehicle(manufacturerSlug, slug).filter((r) =>
    r.applicableYears?.includes(year)
  );
}

export function getAvailableYears(manufacturerSlug: string, slug: string) {
  const list = getRecallsForVehicle(manufacturerSlug, slug);
  const years = new Set<number>();
  list.forEach((r) => r.applicableYears?.forEach((y) => years.add(y)));
  return Array.from(years).sort((a, b) => b - a);
}
