import { Recall } from "./types";

// 아래 데이터는 국토교통부 발표를 인용한 언론 보도 및 자동차리콜센터(car.go.kr) 공개 정보를 바탕으로
// 정리한 실제 리콜 사례입니다. 각 항목의 출처(source/sourceUrl)를 통해 원문을 확인할 수 있습니다.
// 정확한 개별 차량의 리콜 대상 및 조치 여부는 반드시 자동차리콜센터에서 확인해야 합니다.
export const recalls: Recall[] = [
  {
    id: "r-palisade-seat-2026",
    vehicleSlugs: ["hyundai/palisade"],
    manufacturer: "현대",
    affectedModelsText: "팰리세이드, 팰리세이드 하이브리드(미판매 재고 포함) 5만7,987대",
    title: "2·3열 전동시트 제어기 소프트웨어 관련 리콜",
    recallDate: "2026-03-20",
    applicableYears: [2023, 2024, 2025],
    defect:
      "2·3열 전동시트 제어기 소프트웨어 설계가 미흡해 탑승자나 사물과의 접촉을 정상적으로 감지하지 못하는 문제가 확인됨",
    risk: "전동시트 작동 중 탑승자나 사물이 끼이는 안전사고로 이어질 가능성",
    remedy:
      "무선 소프트웨어 업데이트(OTA)를 통해 전동시트 작동 해제 방식 변경, 접촉 감지 구간 확대, 자동 접힘 기능 작동 조건 강화",
    affectedCount: 57987,
    recallType: "자발적 리콜",
    status: "related",
    source: "아주경제 (국토교통부 발표 인용)",
    sourceUrl: "https://www.ajunews.com/view/20260324083104954",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-palisade-seatbelt-2026",
    vehicleSlugs: ["hyundai/palisade"],
    manufacturer: "현대",
    affectedModelsText: "팰리세이드 4만1,143대",
    title: "3열 좌측 안전띠 버클 배선 관련 리콜",
    recallDate: "2026-04-10",
    applicableYears: [2023, 2024, 2025],
    defect:
      "3열 좌측 안전띠 버클 배선 설계가 미흡해 안전띠를 체결하지 않아도 경고장치가 작동하지 않는 문제",
    risk: "탑승자가 안전띠 미체결 상태를 인지하지 못할 가능성",
    remedy: "국토교통부 발표 기준 시정조치 진행 (세부 방법은 공식 출처 확인)",
    affectedCount: 41143,
    recallType: "자발적 리콜",
    status: "related",
    source: "아주경제 (국토교통부 발표 인용)",
    sourceUrl: "https://www.ajunews.com/view/20260324083104954",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-sonata-airbag-2024",
    vehicleSlugs: ["hyundai/sonata"],
    manufacturer: "현대",
    affectedModelsText: "쏘나타 등 2개 차종 31만2,744대",
    title: "에어백 제어장치 설계오류 관련 리콜",
    recallDate: "2024-10-11",
    defect: "에어백 제어장치 설계오류로 내부 소자가 손상되어 에어백이 전개되지 않을 가능성",
    risk: "사고 발생 시 에어백이 정상적으로 전개되지 않을 가능성",
    remedy:
      "제작사가 소유자에게 우편 및 휴대전화 문자로 시정 방법을 안내하며, 사전에 자비로 수리한 경우 비용 보상 신청 가능",
    affectedCount: 312744,
    recallType: "리콜",
    status: "related",
    source: "뉴스핌 (국토교통부 발표 인용)",
    sourceUrl: "https://www.newspim.com/news/view/20241008001080",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-avante-cvt-2026",
    vehicleSlugs: ["hyundai/avante"],
    manufacturer: "현대",
    affectedModelsText: "아반떼 13만283대",
    title: "무단변속기(CVT) 내부 이물질 유입 관련 리콜",
    recallDate: "2026-01-19",
    defect: "무단변속기 부품 내부로 이물질이 유입되어 구동력이 정상적으로 전달되지 않을 가능성",
    risk: "주행 중 구동력이 끊길 가능성",
    remedy:
      "자동변속기 부품을 정비해 이물질 유입을 방지하는 시정조치 진행. 우편·문자 안내, 사전 자비 수리 시 비용 보상 신청 가능",
    affectedCount: 130283,
    recallType: "리콜",
    status: "related",
    source: "오토데일리 (국토교통부 발표 인용)",
    sourceUrl: "https://www.autodaily.co.kr/news/articleView.html?idxno=540775",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-sorento-hev-seatbelt-2023",
    vehicleSlugs: ["kia/sorento"],
    manufacturer: "기아",
    affectedModelsText: "쏘렌토 하이브리드(HEV) 8만1,608대",
    title: "앞좌석 안전띠 조절장치(프리텐셔너) 관련 리콜",
    recallDate: "2023-08-16",
    defect: "앞좌석 안전띠 조절장치 내부 부품(가스발생기) 불량",
    remedy: "자발적 시정조치(리콜) 실시",
    affectedCount: 81608,
    recallType: "자발적 리콜",
    status: "related",
    source: "뉴시스",
    sourceUrl: "https://www.newsis.com/view/NISX20230816_0002415834",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-carnival-fire-2026",
    vehicleSlugs: ["kia/carnival"],
    manufacturer: "기아",
    affectedModelsText: "카니발 9만9,889대",
    title: "엔진 내부 부품 체결 불량 관련 리콜 (화재 위험)",
    recallDate: "2026-08-06",
    defect: "엔진 내부 부품의 너트 체결 불량으로 연료가 누유되어 화재가 발생할 가능성",
    risk: "주행 중 또는 주정차 중 화재 발생 가능성",
    remedy: "국토교통부 발표 기준 시정조치 진행 (세부 방법은 공식 출처 확인)",
    affectedCount: 99889,
    recallType: "리콜",
    status: "related",
    source: "경향신문 (국토교통부 발표 인용)",
    sourceUrl: "https://www.khan.co.kr/article/202608060730001",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-gv80-isg-2020",
    vehicleSlugs: ["genesis/gv80"],
    manufacturer: "제네시스",
    affectedModelsText: "GV80 823대",
    title: "ISG(스탑앤고) 소프트웨어 오류 관련 리콜",
    recallDate: "2020-02-27",
    defect:
      "ISG 장치의 소프트웨어 오류로 인한 변속 불량. 주차 중 기어를 P로 두면 ISG 작동으로 시동이 꺼지고, 재시동 후 D→R→D 순으로 기어를 조작하면 D 모드에서도 차량이 후진하는 현상 발생",
    risk: "운전자 의도와 다르게 차량이 후진할 가능성",
    remedy: "소프트웨어 업데이트 실시",
    affectedCount: 823,
    recallType: "리콜",
    status: "related",
    source: "모터그래프",
    sourceUrl: "https://www.motorgraph.com/news/articleView.html?idxno=25179",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-bmw-520d-egr-2021",
    vehicleSlugs: ["bmw/520d"],
    manufacturer: "BMW",
    affectedModelsText: "BMW 520d 등 31개 차종 22만1,172대",
    title: "배기가스재순환장치(EGR쿨러) 균열 관련 리콜",
    recallDate: "2021-03-31",
    defect: "2017년 이후 개선된 EGR쿨러 일부 제품에서 균열이 발생해 화재 위험이 있는 것으로 확인",
    risk: "냉각수 누수 및 화재 발생 가능성",
    remedy:
      "냉각수 누수 위험도가 높은 차량(약 10만7,731대)은 EGR쿨러 교체, 최근 생산된 EGR쿨러 장착 차량(약 11만3,441대)은 점검 후 필요시 교체",
    affectedCount: 221172,
    recallType: "리콜",
    status: "related",
    source: "뉴시스 (국토교통부 발표 인용)",
    sourceUrl: "https://www.newsis.com/view/NISX20210331_0001390672",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-tesla-hood-2024",
    vehicleSlugs: ["tesla/model-3"],
    manufacturer: "테슬라",
    affectedModelsText: "테슬라 Model 3·Model Y 등 4개 차종 6만6,489대",
    title: "후드 오픈 감지 소프트웨어 오류 관련 리콜",
    recallDate: "2024-08-22",
    defect: "후드 관련 소프트웨어 오류로 주행 중 후드가 열려 있어도 운전자가 이를 감지하지 못할 가능성",
    risk: "주행 중 후드가 열려 시야 확보에 지장을 줄 가능성",
    remedy: "무선 소프트웨어 업데이트(OTA) 등 국토교통부 발표 기준 조치 (세부 방법은 공식 출처 확인)",
    affectedCount: 66489,
    recallType: "자발적 리콜",
    status: "related",
    source: "경기일보 (국토교통부 발표 인용)",
    sourceUrl: "https://www.kyeonggi.com/article/20240821580001",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-tesla-seatbelt-2022",
    vehicleSlugs: ["tesla/model-3"],
    manufacturer: "테슬라",
    affectedModelsText: "테슬라 Model 3·Model Y 3만3,337대",
    title: "안전벨트 미착용 경고음 미작동 관련 리콜",
    recallDate: "2022-02-17",
    defect: "제어장치 소프트웨어 오류로 안전벨트를 착용하지 않아도 경고음이 울리지 않는 문제",
    risk: "안전벨트 미착용 상태로 주행할 가능성",
    remedy: "테슬라 서비스센터 무상 수리 또는 무선 소프트웨어 업데이트로 조치",
    affectedCount: 33337,
    recallType: "리콜",
    status: "related",
    source: "매일신문",
    sourceUrl: "https://www.imaeil.com/page/view/2022021709075461319",
    updatedAt: "2026-09-12",
  },

  // 아래부터는 한국교통안전공단이 공공데이터포털(data.go.kr)에 공개한
  // "자동차결함 리콜현황" 파일데이터(2025-12-31 기준, 이용허락범위 제한 없음)를
  // 근거로 자동 생성한 항목입니다. 같은 리콜사유·리콜개시일을 공유하는 트림들은
  // 하나의 리콜로 묶었고, 생산기간(부터/까지)에 걸친 연도를 applicableYears로 반영했습니다.
  // 원본 파일: data/recalls-2025-raw.csv, 정리 스크립트: scripts/build-official-recalls.py
  {
    id: "r-palisade-20250905",
    vehicleSlugs: ["hyundai/palisade"],
    manufacturer: "현대",
    affectedModelsText: "팰리세이드(LX3), 팰리세이드 하이브리드(LX3 HEV)",
    title: "휠 고정용 너트 체결 불량 관련 리콜",
    recallDate: "2025-09-05",
    productionStart: "2025-01",
    productionEnd: "2025-07",
    applicableYears: [2025],
    defect:
      "팰리세이드(LX3), 팰리세이드HEV (LX3 HEV) 일부 차량에서 휠 고정용 너트 체결 작업 불량으로 주행 중 너트 풀림에 의한 휠 이탈 발생 가능성이 있는 결함 사항 확인",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-palisade-20250916",
    vehicleSlugs: ["hyundai/palisade"],
    manufacturer: "현대",
    affectedModelsText: "팰리세이드(LX3), 팰리세이드 하이브리드(LX3 HEV)",
    title: "전방 후드 래치 설계 미흡 관련 리콜",
    recallDate: "2025-09-16",
    productionStart: "2024-12",
    productionEnd: "2025-07",
    applicableYears: [2024, 2025],
    defect:
      "일부 차량에서 전방 후드 래치 설계 미흡으로 인해 과속방지턱을 주행할 경우 전방 후드 열림 현상이 발생할 수 있으며, 전방 시야 확보가 불가하여 주행 안정성 저하 가능성이 있는 결함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-avante-20250610",
    vehicleSlugs: ["hyundai/avante"],
    manufacturer: "현대",
    affectedModelsText: "아반떼(HD)",
    title: "운전석 에어백 인플레이터 파손 관련 리콜",
    recallDate: "2025-06-10",
    productionStart: "2008-10",
    productionEnd: "2009-07",
    applicableYears: [2008, 2009],
    defect:
      "아반떼(HD) 등 2차종 일부 차량에서 운전석 에어백 전개시 인플레이터의 과도한 내부 압력 증가로 인해 인플레이터 용기가 파손되어 승객이 상해를 입을 가능성이 있는 결함",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-santafe-20250709",
    vehicleSlugs: ["hyundai/santafe"],
    manufacturer: "현대",
    affectedModelsText: "싼타페 하이브리드(MX5 HEV)",
    title: "2열 시트 배선 간섭 사이드 에어백 오작동 관련 리콜",
    recallDate: "2025-07-09",
    productionStart: "2024-04",
    productionEnd: "2024-04",
    applicableYears: [2024],
    defect:
      "싼타페 하이브리드(MX5 HEV) 일부 차량에서 차체 하단 와이어링(배선) 경로 설계 불량으로 인해 2열 시트를 접을 시 와이어링(배선)과 시트 회전 장치가 간섭되어 2열 사이드 에어백 오전개 및 미전개 가능성이 있는 결함 사항이 확인",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-sorento-20250124",
    vehicleSlugs: ["kia/sorento"],
    manufacturer: "기아",
    affectedModelsText: "쏘렌토 하이브리드(MQ4 HEV PE), 쏘렌토 (MQ4 PE)",
    title: "바디도메인 제어장치 소프트웨어 오류(전조등 꺼짐) 관련 리콜",
    recallDate: "2025-01-24",
    productionStart: "2023-07",
    productionEnd: "2024-07",
    applicableYears: [2023, 2024],
    defect:
      "바디도메인 제어장치 소프트웨어 오류로 인해 주행 초기 소프트웨어가 리셋되어 재동작하는 경우 전조등이 일시적으로 꺼졌다 켜질 가능성",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-carnival-20251212",
    vehicleSlugs: ["kia/carnival"],
    manufacturer: "기아",
    affectedModelsText: "카니발 하이브리드(KA4 HEV)",
    title: "하이브리드 통합제어기(HPCU) 소손 가능성 관련 리콜",
    recallDate: "2025-12-12",
    productionStart: "2023-12",
    productionEnd: "2025-04",
    applicableYears: [2023, 2024, 2025],
    defect:
      "카니발 하이브리드(KA4 HEV) 일부 차량에서 하이브리드 통합 제어기(HPCU) 소프트웨어 설계 오류로 동절기 원격시동 및 히터 작동 등 전장 고부하 시 하이브리드 통합 제어기(HPCU) 소손 발생 가능성이 있는 결함이 발견됨. HPCU(Hybrid Power Control Unit)는 모터 구동을 위해 인버터, LDC 등을 포함해 제어하는 장치",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-gv80-20250320",
    vehicleSlugs: ["genesis/gv80"],
    manufacturer: "제네시스",
    affectedModelsText: "GV80(JX)",
    title: "계기판 표시 오류 관련 리콜",
    recallDate: "2025-03-20",
    productionStart: "2023-01",
    productionEnd: "2023-10",
    applicableYears: [2023],
    defect:
      "G80(RG3), GV80(JX), GV70(JK), GV70 EV(JK EV) 일부 차량에서 계기판(8인치 계기판 적용 차량) 제어기 소프트웨어 설계 오류로 인해 초기 시동 시 간헐적으로 계기판 이미지가 표출되지 않아 안전기준에 적합하지 않는 사항이 확인됨",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-520d-20251024",
    vehicleSlugs: ["bmw/520d"],
    manufacturer: "BMW",
    affectedModelsText: "520d, 520d xDrive",
    title: "스타터 모터 수분 유입 관련 리콜",
    recallDate: "2025-10-24",
    productionStart: "2016-05",
    productionEnd: "2020-06",
    applicableYears: [2016, 2017, 2018, 2019, 2020],
    defect: "스타터 모터 내 수분이 유입될 가능성이 확인되었습니다.",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-520d-20251204",
    vehicleSlugs: ["bmw/520d"],
    manufacturer: "BMW",
    affectedModelsText: "BMW 520d, BMW 520d Touring, BMW 520d xDrive",
    title: "TAKATA 에어백 스티어링휠 관련 리콜",
    recallDate: "2025-12-04",
    productionStart: "2010-05",
    productionEnd: "2016-10",
    applicableYears: [2010, 2011, 2012, 2013, 2014, 2016],
    defect:
      "최초 판매 당시에는 TAKATA 에어백이 적용되지 않은 스티어링 휠로 출고되었으나, 이후 BMW가 승인한 교체 부품 중 TAKATA 에어백이 적용된 스포츠/M 스포츠 스티어링 휠을 고객이 장착했을 가능성이 확인됨. 해당 휠은 질산암모늄 추진제를 사용해 고온다습 환경에 장기간 노출 시 인플레이터 내부 추진제가 변형될 수 있음",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-model3-20250114",
    vehicleSlugs: ["tesla/model-3"],
    manufacturer: "테슬라",
    affectedModelsText: "Model 3",
    title: "타이어공기압경고장치(TPMS) 소프트웨어 오류 관련 리콜",
    recallDate: "2025-01-14",
    productionStart: "2024-04",
    productionEnd: "2024-08",
    applicableYears: [2024],
    defect:
      "소프트웨어 오류로 TPMS(타이어공기압경고장치)에 이상이 감지된 뒤 차량이 주행 사이클 사이에서 꺼지거나 대기 상태가 되면, TPMS 이상 경고등이 지속적으로 표시되지 않아 관련 안전기준을 준수하지 않는 문제",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
  {
    id: "r-model3-20250205",
    vehicleSlugs: ["tesla/model-3"],
    manufacturer: "테슬라",
    affectedModelsText: "Model 3",
    title: "전원 과전류로 인한 후방카메라 미작동 관련 리콜",
    recallDate: "2025-02-05",
    productionStart: "2024-01",
    productionEnd: "2024-08",
    applicableYears: [2024],
    defect:
      "일부 차량에서 전원 공급 시 과도한 전류가 발생해 차량 컴퓨터가 손상될 가능성이 확인됨. 이로 인해 후방카메라 디스플레이가 정상적으로 작동하지 않을 수 있어 후방보행자 안전장치 관련 안전기준을 준수하지 않는 문제",
    remedy: "정확한 조치(시정) 방법은 자동차리콜센터 공식 안내 또는 제작사 서비스센터를 통해 확인하실 수 있습니다.",
    recallType: "리콜",
    status: "related",
    source: "한국교통안전공단 자동차결함 리콜현황 (2025-12-31 기준, data.go.kr 공공데이터)",
    sourceUrl: "https://www.data.go.kr/data/3048950/fileData.do",
    updatedAt: "2026-09-12",
  },
];

export function getRecallsForVehicle(manufacturerSlug: string, slug: string) {
  const key = `${manufacturerSlug}/${slug}`;
  return recalls
    .filter((r) => r.vehicleSlugs.includes(key))
    .sort((a, b) => (a.recallDate < b.recallDate ? 1 : -1));
}

export function getRecallsForVehicleYear(
  manufacturerSlug: string,
  slug: string,
  year: number
) {
  return getRecallsForVehicle(manufacturerSlug, slug).filter((r) =>
    r.applicableYears?.includes(year)
  );
}

export function getAvailableYears(manufacturerSlug: string, slug: string) {
  const list = getRecallsForVehicle(manufacturerSlug, slug);
  const years = new Set<number>();
  list.forEach((r) => r.applicableYears?.forEach((y) => years.add(y)));
  return Array.from(years).sort((a, b) => b - a);
}
