import { Vehicle } from "./types";

export const vehicles: Vehicle[] = [
  {
    id: "hyundai-palisade",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "팰리세이드",
    englishName: "Palisade",
    slug: "palisade",
    aliases: [
      "펠리세이드",
      "팔리세이드",
      "펠리세이",
      "palisade",
      "현대 팰리세이드",
      "더뉴팰리세이드",
      "더 뉴 팰리세이드",
    ],
    category: "대형 SUV",
    soldSince: 2018,
    description: "현대자동차의 대형 SUV. 2018년 출시 이후 2022년 페이스리프트(더 뉴 팰리세이드)를 거쳤습니다.",
  },
  {
    id: "hyundai-sonata",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "쏘나타",
    englishName: "Sonata",
    slug: "sonata",
    aliases: ["소나타", "sonata", "현대 쏘나타", "쏘나타 디 엣지", "디엣지"],
    category: "중형 세단",
    soldSince: 1985,
    description: "현대자동차의 중형 세단. 현재 8세대(DN8) 모델이 판매 중입니다.",
  },
  {
    id: "hyundai-avante",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "아반떼",
    englishName: "Avante / Elantra",
    slug: "avante",
    aliases: ["아반테", "avante", "elantra", "엘란트라", "현대 아반떼"],
    category: "준중형 세단",
    soldSince: 1990,
    description: "현대자동차의 준중형 세단. 해외에서는 엘란트라(Elantra)로 판매됩니다.",
  },
  {
    id: "hyundai-santafe",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "싼타페",
    englishName: "Santa Fe",
    slug: "santafe",
    aliases: ["산타페", "santa fe", "싼타페", "현대 싼타페"],
    category: "중형 SUV",
    soldSince: 2000,
    description: "현대자동차의 중형 SUV.",
  },
  {
    id: "kia-sorento",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "쏘렌토",
    englishName: "Sorento",
    slug: "sorento",
    aliases: ["소렌토", "sorento", "기아 쏘렌토", "쏘렌토 하이브리드"],
    category: "중형 SUV",
    soldSince: 2002,
    description: "기아의 중형 SUV. 하이브리드 모델도 함께 판매됩니다.",
  },
  {
    id: "kia-carnival",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "카니발",
    englishName: "Carnival / Sedona",
    slug: "carnival",
    aliases: ["carnival", "sedona", "기아 카니발"],
    category: "미니밴",
    soldSince: 1998,
    description: "기아의 대표 미니밴(RV).",
  },
  {
    id: "genesis-gv80",
    manufacturer: "제네시스",
    manufacturerSlug: "genesis",
    modelName: "GV80",
    englishName: "GV80",
    slug: "gv80",
    aliases: ["gv80", "지브이80", "제네시스 gv80"],
    category: "대형 SUV",
    soldSince: 2020,
    description: "제네시스의 대형 SUV.",
  },
  {
    id: "bmw-520d",
    manufacturer: "BMW",
    manufacturerSlug: "bmw",
    modelName: "5시리즈 (520d)",
    englishName: "5 Series (520d)",
    slug: "520d",
    aliases: ["520d", "bmw 520d", "비엠더블유 520d", "5시리즈"],
    category: "중형 세단(수입)",
    soldSince: 2010,
    description: "BMW의 중형 세단 5시리즈 디젤 모델.",
  },
  {
    id: "tesla-model3",
    manufacturer: "테슬라",
    manufacturerSlug: "tesla",
    modelName: "Model 3",
    englishName: "Model 3",
    slug: "model-3",
    aliases: ["모델3", "모델 3", "model3", "테슬라 모델3", "테슬라 model 3"],
    category: "전기 세단(수입)",
    soldSince: 2019,
    description: "테슬라의 전기 세단.",
  },

  // 아래부터는 한국교통안전공단 자동차결함 리콜현황(2025-12-31 기준, data.go.kr)에서
  // 2025년에 실제 리콜이 있었던 국산/수입 차종을 추가로 정리한 항목입니다.
  // 생성 스크립트: scripts/build-official-recalls.py
  {
    id: "chevrolet-camaro",
    manufacturer: "쉐보레",
    manufacturerSlug: "chevrolet",
    modelName: "카마로",
    englishName: "Camaro",
    slug: "camaro",
    aliases: ["camaro"],
    category: "스포츠카(수입)",
  },
  {
    id: "chevrolet-sierra",
    manufacturer: "쉐보레",
    manufacturerSlug: "chevrolet",
    modelName: "시에라",
    englishName: "Sierra",
    slug: "sierra",
    aliases: ["sierra"],
    category: "픽업트럭(수입)",
  },
  {
    id: "chevrolet-tahoe",
    manufacturer: "쉐보레",
    manufacturerSlug: "chevrolet",
    modelName: "타호",
    englishName: "Tahoe",
    slug: "tahoe",
    aliases: ["tahoe"],
    category: "대형 SUV(수입)",
  },
  {
    id: "chevrolet-traverse",
    manufacturer: "쉐보레",
    manufacturerSlug: "chevrolet",
    modelName: "트래버스",
    englishName: "Traverse",
    slug: "traverse",
    aliases: ["traverse"],
    category: "대형 SUV(수입)",
  },
  {
    id: "genesis-g80",
    manufacturer: "제네시스",
    manufacturerSlug: "genesis",
    modelName: "G80",
    englishName: "G80",
    slug: "g80",
    aliases: ["지비80", "제네시스 g80"],
    category: "중형 세단",
  },
  {
    id: "genesis-gv60",
    manufacturer: "제네시스",
    manufacturerSlug: "genesis",
    modelName: "GV60",
    englishName: "GV60",
    slug: "gv60",
    aliases: ["지브이60"],
    category: "준중형 SUV(전기)",
  },
  {
    id: "genesis-gv70",
    manufacturer: "제네시스",
    manufacturerSlug: "genesis",
    modelName: "GV70",
    englishName: "GV70",
    slug: "gv70",
    aliases: ["지브이70"],
    category: "준중형 SUV",
  },
  {
    id: "genesis-gv70-ev",
    manufacturer: "제네시스",
    manufacturerSlug: "genesis",
    modelName: "GV70 EV",
    englishName: "GV70 EV",
    slug: "gv70-ev",
    aliases: ["지브이70 이브이", "gv70 electrified"],
    category: "준중형 SUV(전기)",
  },
  {
    id: "hyundai-casper-electric",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "캐스퍼 일렉트릭",
    englishName: "Casper Electric",
    slug: "casper-electric",
    aliases: ["캐스퍼 ev", "캐스퍼이브이"],
    category: "경형 전기 SUV",
  },
  {
    id: "hyundai-county-electric",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "카운티 일렉트릭",
    englishName: "County Electric",
    slug: "county-electric",
    aliases: ["카운티ev"],
    category: "전기버스",
  },
  {
    id: "hyundai-elec-city-fcev",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "일렉시티 수소전기버스",
    englishName: "Elec City FCEV",
    slug: "elec-city-fcev",
    aliases: ["일렉시티"],
    category: "수소전기버스",
  },
  {
    id: "hyundai-i30",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "i30",
    englishName: "i30",
    slug: "i30",
    aliases: ["아이30"],
    category: "해치백",
  },
  {
    id: "hyundai-ioniq5-n",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "아이오닉5 N",
    englishName: "IONIQ 5 N",
    slug: "ioniq5-n",
    aliases: ["ioniq5 n", "아이오닉 5 n"],
    category: "전기차",
  },
  {
    id: "hyundai-ioniq6",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "아이오닉6",
    englishName: "IONIQ 6",
    slug: "ioniq6",
    aliases: ["ioniq6", "아이오닉 6"],
    category: "전기 세단",
  },
  {
    id: "hyundai-ioniq9",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "아이오닉9",
    englishName: "IONIQ 9",
    slug: "ioniq9",
    aliases: ["ioniq9", "아이오닉 9"],
    category: "전기 대형 SUV",
  },
  {
    id: "hyundai-kona",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "코나",
    englishName: "Kona",
    slug: "kona",
    aliases: ["kona"],
    category: "소형 SUV",
  },
  {
    id: "hyundai-nexo",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "넥쏘",
    englishName: "Nexo",
    slug: "nexo",
    aliases: ["nexo", "넥소"],
    category: "수소전기 SUV",
  },
  {
    id: "hyundai-pavise",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "파비스",
    englishName: "Pavise",
    slug: "pavise",
    aliases: ["pavise"],
    category: "대형 트럭",
  },
  {
    id: "hyundai-porter",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "포터",
    englishName: "Porter",
    slug: "porter",
    aliases: ["포터2", "포터ii", "포터 2"],
    category: "소형 트럭",
  },
  {
    id: "hyundai-solati",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "쏠라티",
    englishName: "Solati",
    slug: "solati",
    aliases: ["solati", "솔라티"],
    category: "미니버스",
  },
  {
    id: "hyundai-staria",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "스타리아",
    englishName: "Staria",
    slug: "staria",
    aliases: ["staria"],
    category: "미니밴",
  },
  {
    id: "hyundai-tucson",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "투싼",
    englishName: "Tucson",
    slug: "tucson",
    aliases: ["tucson"],
    category: "준중형 SUV",
  },
  {
    id: "kgmobility-korando",
    manufacturer: "KG모빌리티",
    manufacturerSlug: "kgmobility",
    modelName: "코란도",
    englishName: "Korando",
    slug: "korando",
    aliases: ["korando"],
    category: "준중형 SUV",
  },
  {
    id: "kgmobility-musso-ev",
    manufacturer: "KG모빌리티",
    manufacturerSlug: "kgmobility",
    modelName: "무쏘 EV",
    englishName: "Musso EV",
    slug: "musso-ev",
    aliases: ["musso ev", "무쏘이브이"],
    category: "픽업트럭(전기)",
  },
  {
    id: "kgmobility-tivoli",
    manufacturer: "KG모빌리티",
    manufacturerSlug: "kgmobility",
    modelName: "티볼리",
    englishName: "Tivoli",
    slug: "tivoli",
    aliases: ["tivoli"],
    category: "소형 SUV",
  },
  {
    id: "kia-bongo3",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "봉고3",
    englishName: "Bongo III",
    slug: "bongo3",
    aliases: ["봉고3", "bongo3", "봉고 3"],
    category: "소형 트럭",
  },
  {
    id: "kia-ev3",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "EV3",
    englishName: "EV3",
    slug: "ev3",
    aliases: ["기아 ev3"],
    category: "소형 전기 SUV",
  },
  {
    id: "kia-ev4",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "EV4",
    englishName: "EV4",
    slug: "ev4",
    aliases: ["기아 ev4"],
    category: "준중형 전기차",
  },
  {
    id: "kia-ev9",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "EV9",
    englishName: "EV9",
    slug: "ev9",
    aliases: ["기아 ev9"],
    category: "대형 전기 SUV",
  },
  {
    id: "kia-k3",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "K3",
    englishName: "K3 / Forte",
    slug: "k3",
    aliases: ["포르테", "forte", "k3"],
    category: "준중형 세단",
  },
  {
    id: "kia-niro",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "니로",
    englishName: "Niro",
    slug: "niro",
    aliases: ["niro"],
    category: "소형 SUV(하이브리드)",
  },
  {
    id: "kia-niro-ev",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "니로 EV",
    englishName: "Niro EV",
    slug: "niro-ev",
    aliases: ["niro ev"],
    category: "소형 전기 SUV",
  },
  {
    id: "kia-seltos",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "셀토스",
    englishName: "Seltos",
    slug: "seltos",
    aliases: ["seltos"],
    category: "소형 SUV",
  },
  {
    id: "kia-sportage",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "스포티지",
    englishName: "Sportage",
    slug: "sportage",
    aliases: ["sportage"],
    category: "준중형 SUV",
  },
  {
    id: "renault-arkana",
    manufacturer: "르노코리아",
    manufacturerSlug: "renault",
    modelName: "아르카나",
    englishName: "Arkana",
    slug: "arkana",
    aliases: ["arkana", "아르카나"],
    category: "쿠페형 SUV",
  },
  {
    id: "renault-sm6",
    manufacturer: "르노코리아",
    manufacturerSlug: "renault",
    modelName: "SM6",
    englishName: "SM6",
    slug: "sm6",
    aliases: ["sm6"],
    category: "중형 세단",
  },
  {
    id: "renault-xm3",
    manufacturer: "르노코리아",
    manufacturerSlug: "renault",
    modelName: "XM3",
    englishName: "XM3",
    slug: "xm3",
    aliases: ["xm3"],
    category: "소형 SUV",
  },

  // 아래는 2025년 리콜 데이터엔 없지만(=이 CSV엔 등장하지 않음) 검색량이 많아
  // 차종 정보만 등록해둔 항목입니다. 현재 확인된 리콜은 0건으로 표시되며,
  // 추후 리콜이 발생하면 scripts/build-official-recalls.py로 쉽게 채울 수 있습니다.
  {
    id: "kia-ray",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "레이",
    englishName: "Ray",
    slug: "ray",
    aliases: ["ray", "기아 레이"],
    category: "경형 박스카",
  },
  {
    id: "chevrolet-spark",
    manufacturer: "쉐보레",
    manufacturerSlug: "chevrolet",
    modelName: "스파크",
    englishName: "Spark",
    slug: "spark",
    aliases: ["spark", "쉐보레 스파크", "한국지엠 스파크"],
    category: "경차",
  },
  {
    id: "kia-morning",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "모닝",
    englishName: "Morning / Picanto",
    slug: "morning",
    aliases: ["morning", "picanto", "기아 모닝"],
    category: "경차",
  },
  {
    id: "kia-k5",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "K5",
    englishName: "K5",
    slug: "k5",
    aliases: ["k5", "기아 k5"],
    category: "중형 세단",
  },
  {
    id: "kia-k8",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "K8",
    englishName: "K8",
    slug: "k8",
    aliases: ["k8", "기아 k8"],
    category: "준대형 세단",
  },
  {
    id: "hyundai-grandeur",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "그랜저",
    englishName: "Grandeur",
    slug: "grandeur",
    aliases: ["grandeur", "그랜져"],
    category: "준대형 세단",
  },
  {
    id: "hyundai-casper",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "캐스퍼",
    englishName: "Casper",
    slug: "casper",
    aliases: ["casper", "현대 캐스퍼"],
    category: "경형 SUV",
  },
];

export function findVehicleBySlug(
  manufacturerSlug: string,
  slug: string
): Vehicle | undefined {
  return vehicles.find(
    (v) => v.manufacturerSlug === manufacturerSlug && v.slug === slug
  );
}
