import { Vehicle } from "./types";

export const vehicles: Vehicle[] = [
  {
    id: "hyundai-palisade",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "팰리세이드",
    englishName: "Palisade",
    slug: "palisade",
    aliases: [
      "펠리세이드",
      "팔리세이드",
      "펠리세이",
      "palisade",
      "현대 팰리세이드",
      "더뉴팰리세이드",
      "더 뉴 팰리세이드",
    ],
    category: "대형 SUV",
    soldSince: 2018,
    description: "현대자동차의 대형 SUV. 2018년 출시 이후 2022년 페이스리프트(더 뉴 팰리세이드)를 거쳤습니다.",
  },
  {
    id: "hyundai-sonata",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "쏘나타",
    englishName: "Sonata",
    slug: "sonata",
    aliases: ["소나타", "sonata", "현대 쏘나타", "쏘나타 디 엣지", "디엣지"],
    category: "중형 세단",
    soldSince: 1985,
    description: "현대자동차의 중형 세단. 현재 8세대(DN8) 모델이 판매 중입니다.",
  },
  {
    id: "hyundai-avante",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "아반떼",
    englishName: "Avante / Elantra",
    slug: "avante",
    aliases: ["아반테", "avante", "elantra", "엘란트라", "현대 아반떼"],
    category: "준중형 세단",
    soldSince: 1990,
    description: "현대자동차의 준중형 세단. 해외에서는 엘란트라(Elantra)로 판매됩니다.",
  },
  {
    id: "hyundai-santafe",
    manufacturer: "현대",
    manufacturerSlug: "hyundai",
    modelName: "싼타페",
    englishName: "Santa Fe",
    slug: "santafe",
    aliases: ["산타페", "santa fe", "싼타페", "현대 싼타페"],
    category: "중형 SUV",
    soldSince: 2000,
    description: "현대자동차의 중형 SUV.",
  },
  {
    id: "kia-sorento",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "쏘렌토",
    englishName: "Sorento",
    slug: "sorento",
    aliases: ["소렌토", "sorento", "기아 쏘렌토", "쏘렌토 하이브리드"],
    category: "중형 SUV",
    soldSince: 2002,
    description: "기아의 중형 SUV. 하이브리드 모델도 함께 판매됩니다.",
  },
  {
    id: "kia-carnival",
    manufacturer: "기아",
    manufacturerSlug: "kia",
    modelName: "카니발",
    englishName: "Carnival / Sedona",
    slug: "carnival",
    aliases: ["carnival", "sedona", "기아 카니발"],
    category: "미니밴",
    soldSince: 1998,
    description: "기아의 대표 미니밴(RV).",
  },
  {
    id: "genesis-gv80",
    manufacturer: "제네시스",
    manufacturerSlug: "genesis",
    modelName: "GV80",
    englishName: "GV80",
    slug: "gv80",
    aliases: ["gv80", "지브이80", "제네시스 gv80"],
    category: "대형 SUV",
    soldSince: 2020,
    description: "제네시스의 대형 SUV.",
  },
  {
    id: "bmw-520d",
    manufacturer: "BMW",
    manufacturerSlug: "bmw",
    modelName: "5시리즈 (520d)",
    englishName: "5 Series (520d)",
    slug: "520d",
    aliases: ["520d", "bmw 520d", "비엠더블유 520d", "5시리즈"],
    category: "중형 세단(수입)",
    soldSince: 2010,
    description: "BMW의 중형 세단 5시리즈 디젤 모델.",
  },
  {
    id: "tesla-model3",
    manufacturer: "테슬라",
    manufacturerSlug: "tesla",
    modelName: "Model 3",
    englishName: "Model 3",
    slug: "model-3",
    aliases: ["모델3", "모델 3", "model3", "테슬라 모델3", "테슬라 model 3"],
    category: "전기 세단(수입)",
    soldSince: 2019,
    description: "테슬라의 전기 세단.",
  },
];

export function findVehicleBySlug(
  manufacturerSlug: string,
  slug: string
): Vehicle | undefined {
  return vehicles.find(
    (v) => v.manufacturerSlug === manufacturerSlug && v.slug === slug
  );
}
